### ISSUE TITLE
Can this be used to speed up typing in English?

### ISSUE THREAD

**Issue by infokiller** [mike-fabian/ibus-typing-booster#1]
First, I'd like to thank you for this project- I've been looking for tools to boost my typing for a long time.

Second, I want to verify that my use case is relevant- what I'm looking for is a tool to help me type in **English only**, similar to how the keyboard on my Android phone helps me. I know that most users of input methods do it to type Chinese etc.

Third, I have a few questions. Please let me know if you prefer that I open separate issues. Here goes:
* Does ibus-typing-booster work with any desktop environment? Specifically, I'm using i3.
* Is it possible to use it without fully installing it (i.e without affecting system dirs such as `/usr/bin`).
* How do I trigger it after installing it?

Thanks!

**Comment by mike-fabian** [comment]
Yes, it works for English only.

It works with any desktop environment, i3 should be fine.  

No, I think it cannot work without fully installing it.

After installing it, restart ibus with

ibus restart

Check whether the English typing booster is now listed by ibus:

$ ibus list-engine | grep typing-booster:en_US
  typing-booster:en_US - English - US (Hunspell)

Now start “ibus-setup” and add it as  one of your input methods.

**Comment by mike-fabian** [comment]
![using-ibus-typing-booster-in-english-on-i3-fedora-24](https://cloud.githubusercontent.com/assets/2330175/17851624/2ac1db0c-6863-11e6-829b-f9bd0c1f7fcf.png)

Here is a screenshot using ibus-typing-booster for English on Fedora 24 in i3. It works.
