### ISSUE TITLE
Too slow, not usable 

### ISSUE THREAD

**Issue by ezickler** [mike-fabian/ibus-typing-booster#10]
Hi i read about this first in the f24 or f25 change log and tried it but forgot about it for some time. Today i saw the article on fedora news and thought to give it a try again as i only had to switch layouts. 
Sadly i have to say after 10 minutes i turned it off again. Its soooooo slow it can't handle normal typing speed and in at least two apps it doesn't catch the space. Have to hit it twice. Tried with the tab option on. Think when its turn off space is working but every thing is still slow.
So nice thing but it needs to be much faster. Not necessarily the suggestions but normal input shouldn't have any noticeable delay.

For me i can consider the current state only alpha as it's not usable as an daily input method. 
But still pretty cool thing.  
And i don't know that much about python but i always thought of it as nice language but never considered it for things which needs to be lightning fast like i would expect from this.

Just my thought and feedback. Maybe i just hit a bug. Then i would be happy to see a fix and try it again.

**Comment by mike-fabian** [comment]
Do you have the “Unicode symbols and emoji predictions” option on?
Does it help if you try this?:
http://mike-fabian.github.io/ibus-typing-booster/documentation.html#emoji-mode-quick-toogle

**Comment by ezickler** [comment]
Ohhh nice, that fixed it. Sorry for not properly looking for as solution. I will try to use this as my default input source. Seams really nice.

**Comment by ezickler** [comment]
Sorry just noticed that the missing spaces are still present in the telegram app. Which makes it again really hard to use. 
Emoji off, tab for completion on, german keyboard with direct input.

**Comment by ezickler** [comment]
#12 seams to be the same problem
