### ISSUE TITLE
Shortcuts (like Ctrl+C) do not work on second keyboard layout

### ISSUE THREAD

**Issue by simos** [mike-fabian/ibus-typing-booster#107]
Thanks for fixing the previous issue with the second keyboard layout on GNOME X11! :-).

I tried the new package of ibus-typing-booster for 2.9.0 by @gunnarhj ([ibus-typing booster PPA](https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-typing-booster)).

Keyboard shorts like Ctrl+C or Ctrl+A and other application shortcuts like Alt+F (_File menu_) are captured by _ibus-typing-booster_, and are not released to the application.

Specifically, 
1. I have two keyboard layouts, `us` and `gr`, in this order. 
2. I switch to `gr`, then switch to _IBus typing booster_, therefore I can type Greek with predictive typing.
3. I open `gedit`. When I press `Alt+A` to Select All, the letter `α` is printed. Same with other shortcuts that involve `Alt` or `Ctrl`.

**Comment by mike-fabian** [comment]
> When I press Alt+A to Select All

I guess you mean Control+a, not Alt+A here?

**Comment by simos** [comment]
> I guess you mean Control+a, not Alt+A here?

Yes, `Contrl+A` to _Select All_ (was a typo).

**Comment by mike-fabian** [comment]
Does it happen *only* with the gr layout?

**Comment by mike-fabian** [comment]
I think I can reproduce it ...

**Comment by mike-fabian** [comment]
Seems to happen only with he gr layout and the windowmanager/desktop doesn’t seem to matter.

**Comment by mike-fabian** [comment]
I hope this will fix it:

https://github.com/mike-fabian/ibus-typing-booster/commit/90286c15806ec21a11d136542bab2e90bc117834

It seems to work for me, I just want to test a bit more before I make the 2.9.1 release.

**Comment by gunnarhj** [comment]
I added that commit to the package in [this PPA](https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-typing-booster), so @simos more easily can help to test.

**Comment by mike-fabian** [comment]
> I added that commit to the package in [this PPA](https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-typing-booster), so @simos more easily can help to test.

Thank you!

**Comment by simos** [comment]
Thanks @mike-fabian and @gunnarhj.

I updated the package from the PPA and then I restarted my X11 session for the new _ibus-typing-booster_ to take effect. 

The issue has been fixed for me. I was able to use shortcuts (Ctrl+C, Ctrl+A, Alt+F to open the File menu). 

Thank you both!

**Comment by mike-fabian** [comment]
I have release 2.9.1 with this fix (and another bugfix) now:

https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.9.1

**Comment by nkk64** [comment]
Hi, same issue here with Georgian - ctrl-c, ctrl-v, ctrl-a not working. (I checked Greek too and it's OK). 

Upgraded to Ubuntu Jammy Jellyfish (development branch) and to my surprise I HAVE to have ibus because Zoom requires it - I used to use XKBLAYOUT/XKBOPTIONS for ubuntu 20.04.

**Comment by gunnarhj** [comment]
@nkk64: This issue was closed almost two years ago. If you experience a similar issue with Georgian, please submit a new issue.

It's true that the .deb package for Zoom includes an annoying (and redundant) dependency on ibus. But, considering that you seem to use `ibus-typing-booster`, how is that dependency a problem for you? You need to have ibus-daemon running anyway to be able to use `ibus-typing-booster`.

**Comment by nkk64** [comment]
Sorry, I thought the bug being totally similar to the greek layout one did
not deserve new bug status.

Anyway, for over 10 years I've been using fluxbox (on top of xubuntu
installation) and had setup switching using xkb settings in
/etc/default/keyboard using capslock to change layouts with no graphical
switcher at all (not sure whether ibus was installed). Today I was foolish
enough to upgrade to 22.04 and  I found ibus switcher automagically sitting
in my slit. Tried to remove ibus - found that it's zoom dependance. I could
start using it and get used to some other switch shortcut (there's no
option for capslock switch I guess) but without ctrl-c/ctrl-v working it's
a sheer nightmare.

Anyway, I guess my use case (fluxbox+Georgian) is quite unique, so I'll try
to find a workaround myself. If not, I'll post new bug.

Thanks for quick answer.
Regards,
Nick

**Comment by gunnarhj** [comment]
@nkk64: If you really got ibus installed involuntarily due to Zoom, and `ibus-typing-booster` is merely a way to handle the situation, there is a simpler way. You can disable ibus, so to speak, so it's not started automatically at login:

    im-config -n none

**Comment by nkk64** [comment]
Thanks - you saved my day :) Now all is working fine in the old way without
graphical switcher.

So I'll not be posting bug for Georgian (which imho still is apparently
there), though it's strange that ctrl-c behaviour  is layout dependent. I
fear there may be some similar complaints after 22.04 official release is
out later in April.

**Comment by mike-fabian** [comment]
> Hi, same issue here with Georgian - ctrl-c, ctrl-v, ctrl-a not working. (I checked Greek too and it's OK).
> 
> Upgraded to Ubuntu Jammy Jellyfish (development branch) and to my surprise I HAVE to have ibus because Zoom requires it - I used to use XKBLAYOUT/XKBOPTIONS for ubuntu 20.04.

This seems more like a fluxbox problem to me.

I can reproduce the problem with the Georgian keyboard layout when using fluxbox on Fedora 36 and you are right that it works for Greek. But I can still reproduce the problem with fluxbox on Fedora 36 when ibus is not used at all.

And on Gnome (Xorg) in Fedora 36 it works both for the Greek **and** for the Georgian keyboard layout, when using the plain keyboard layouts as well as when using them with ibus-typing-booster is used.

When using the Greek keyboard layout and typing the key where `a` is on the us layout, you get `α`, when doing this with the Georgian layout you get `ა`.

I.e. when typing Control+a on a Greek layout,  what is actually typed is Control+α, when doing this on a Georgian layout what is actually typed is Control+ა.

My fix for Greek in 

https://github.com/mike-fabian/ibus-typing-booster/commit/90286c15806ec21a11d136542bab2e90bc117834

works as follows: When typing Control + any single character which has a Unicode representation commit the current preedit if there is one and pass that key event through to the application. If there is nothing to commit, pass it through directly.

So Gnome or Fluxbox receive  Control+α for Greek or Control+ა for Georgian. In Gnome both seems to be translated to Control+a which then selects all text in gedit. 

In Fluxbox however, this works only for Greek.

Seems like a Fluxbox problem to me.

**Comment by mike-fabian** [comment]
Video made with Gnome (Xorg) on Fedora 36, showing that this works both for Greek and Georgian keyboard layouts when using ibus-typing-booster, Control+a commits and selects the whole text in Gedit:

https://user-images.githubusercontent.com/2330175/161964688-c880645e-79a4-4427-a683-2207a0ea19c3.mp4

**Comment by mike-fabian** [comment]
Actually it fails **both** for Greek **and** Georgian keyboard layouts in Fluxbox on Fedora 36 when **not** using ibus.

**Comment by mike-fabian** [comment]
But when I use ibus in Fluxbox in Fedora 36, it starts to work for Greek but not for Georgian.

**Comment by mike-fabian** [comment]
Actually doing the following fixes the problem for the Georgian keyboard layout when using ibus:

```
gsettings set  org.freedesktop.ibus.general xkb-latin-layouts "['ara', 'bg', 'cz', 'dev', 'gr', 'gur', 'in', 'jp(kana)', 'mal', 'mkd', 'ru', 'ua', 'ge']"
ibus restart
```

(`'ge'` has been added there!)

Thanks to Fujiwara San for the hint.

**Comment by nkk64** [comment]
Wow, great news! Thank you, Mike (and Fujiwara San).

**Comment by mike-fabian** [comment]
https://github.com/ibus/ibus/issues/2404

**Comment by mike-fabian** [comment]
https://github.com/ibus/ibus/pull/2405
