### ISSUE TITLE
This tool doesn't have an installation guide

### ISSUE THREAD

**Issue by hillonyechekwa** [mike-fabian/ibus-typing-booster#120]
I don't know maybe I'm not getting the hang of it or something but the doc of this tool has no installation guide. Is this something done on purpose because i can't for the life of me figure out how to install this tool on my system. There is only a guide for how to configure it in the system but not how to install it. Please can anyone rectify this issue

**Comment by mike-fabian** [comment]
On some systems like Fedora, FreeBSD, OpenSUSE packages are available,
see the links at

http://mike-fabian.github.io/ibus-typing-booster/index.html

Is you system not among these? Then you may need to install from source.

There is some information on how to install from source here:

http://mike-fabian.github.io/ibus-typing-booster/development.html

See especially the section “Building and installing using the source”.

If that doesn’t work for you or you have a different system from those
listed there, tell me what is going wrong, I’ll try to help you.


Or maybe you have it already installed and are just looking how to enable
it in your desktop?

Then

http://mike-fabian.github.io/ibus-typing-booster/documentation.html#adding-to-desktop

may help.

**Comment by mike-fabian** [comment]
Ping 🏓

**Comment by hillonyechekwa** [comment]
Thanks @mike-fabian

**Comment by mike-fabian** [comment]
That means it works for you?

**Comment by mike-fabian** [comment]
Thanks to Gunnar Hjalmarsson, packages are available now also for Ubuntu and Debian.

https://launchpad.net/ubuntu/+source/ibus-typing-booster
https://packages.debian.org/sid/ibus-typing-booster

could you successfully install ibus-typing-booster?

**Comment by mike-fabian** [comment]
Closing because there is no reply. Maybe it works.
