### ISSUE TITLE
alternate keyboard shortcut

### ISSUE THREAD

**Issue by rickysarraf** [mike-fabian/ibus-typing-booster#15]
Hi,

Should "Enable Suggestions by Tab key" be user configurable ?

I found one use case where it is buggy. Under HexChat, Tab is used for IRC Handle auto-completion, which is where ibus completely fails. HexChat overrides and registers it as a regular Tab.

Steps:
1. Enable "Enable Suggestions by Tab key"
2. In HexChat, pick a name and hit Tab for auto-completion.

Since Tab auto-completion is common in IRC, I would expect ibus to fix it. And the fix would be to give the user the choice to select a different key, if need be.

**Comment by mike-fabian** [comment]
Release  2.3.0 https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.3.0
has configurable keybindings for several commands now, including for "Enable Suggestions by Tab key".
Does that work for you?
