### ISSUE TITLE
Is there any way to install this on Debian 10 - Buster?  

### ISSUE THREAD

**Issue by richaardvark** [mike-fabian/ibus-typing-booster#150]
I'm running the latest version of MX Linux (19.3) which is based on Debian 10.6 (Buster). MX Linux is one of the [most popular and most widely used distros out there](https://distrowatch.com/dwres.php?resource=popularity) but unfortunately is stuck with Ibus 1.5.19-4 and this needs > 1.5.22.  

Am I just totally out of luck here?

**Comment by mike-fabian** [comment]
No, it doesn't really require ibus > 1.5.22.

You should be able to build from source, see:

http://mike-fabian.github.io/ibus-typing-booster/development.html

**Comment by mike-fabian** [comment]
![Screenshot](https://user-images.githubusercontent.com/2330175/99435026-d9304680-290f-11eb-9ebc-7af67aea957a.png)

**Comment by mike-fabian** [comment]
Closing because this is not a problem of ibus-typing-booster.
