### ISSUE TITLE
can't write in apps menu or with alt+F2

### ISSUE THREAD

**Issue by sara-rodriguez** [mike-fabian/ibus-typing-booster#152]
If If try to write for search a program or open and application is given the options to choice but If can't see any text, so I can't write and If find/open and application.

**Comment by mike-fabian** [comment]
I am not sure what you mean. Are you trying to type in the “Run a Command“ dialog, i.e. this one?:

![Screenshot](https://user-images.githubusercontent.com/2330175/103505692-2aae7980-4e5b-11eb-8243-b12b533f1242.png)

**Comment by sara-rodriguez** [comment]
The problem was solved upgrading Ubuntu to the 20.10 release, but what happened is that when I write in the screen above it doesn't appears any letter, just the options, and if I've tried to select any options it doesn't appears nothing wrote.

**Comment by mike-fabian** [comment]
So it works fine for you now and we can close this?

**Comment by sara-rodriguez** [comment]
Yes, this topic can be closed.

**Comment by mike-fabian** [comment]
OK, closing, thank you!
