### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by renatoliveira** [mike-fabian/ibus-typing-booster#154]
On the using Gnome3 documentation it might be helpful to mention that if Typing Booster does not show up on the "Add Input Source" window the user might have to restart their session (just log off and log in again). That was the case for me when installing on Pop! OS and Manjaro.

Now, I usually would have opened a pull request to add this, but I can't find the repository with the documentation website. 😅

**Comment by mike-fabian** [comment]
It is the same repository, on the gh-pages branch.
