### ISSUE TITLE
emoji-picker is unusable with dark themes

### ISSUE THREAD

**Issue by yselkowitz** [mike-fabian/ibus-typing-booster#16]
When a dark theme is in use (e.g. the dark variant of Adwaita on GNOME 3, or a dedicated dark theme such as BlackMATE, Breeze-dark, or HighContrast), the character display area of emoji-picker does not go dark.  This results in either a very light or white emoji "text" on top of a white background, making it practically unusable.

**Comment by mike-fabian** [comment]
I just tried it. You mean this, I guess?:

![emoji-picker](https://cloud.githubusercontent.com/assets/2330175/23635533/ae0f6d00-02d0-11e7-8810-aa92241f8ec4.png)

I’ll look into it ...

**Comment by yselkowitz** [comment]
Yes, but with some dark themes it's even worse.

**Comment by mike-fabian** [comment]
I think I I found a solution.

![emoji-picker](https://cloud.githubusercontent.com/assets/2330175/23656757/4076836c-033b-11e7-8934-9e20875b8ed2.png)

**Comment by mike-fabian** [comment]
I made the screenshot above after changing this:

https://github.com/mike-fabian/ibus-typing-booster/commit/3819a4535a94683dcd46e9ee7c6c2a43ec31ec12

So this seems to work.

**Comment by yselkowitz** [comment]
Thanks!
