### ISSUE TITLE
Make shortcuts sortable by the user and by field

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#163]
Please, add this feature, if it does not take you so much effort. Thanks!

**Comment by mike-fabian** [comment]
It seems much easier than I thought. This small change seems to do it:

```diff --git a/setup/main.py b/setup/main.py
index acdd4f5..07df9eb 100644
--- a/setup/main.py
+++ b/setup/main.py
@@ -1033,20 +1033,22 @@ class SetupUI(Gtk.Window):
         current_shortcuts = self.tabsqlitedb.list_user_shortcuts()
         for i, shortcut in enumerate(current_shortcuts):
             self._shortcut_treeview_model.append(shortcut)
-        self._shortcut_treeview.append_column(
-            Gtk.TreeViewColumn(
-                # Translators: Column heading of the table listing the
-                # existing shortcuts
-                _('Shortcut'),
-                Gtk.CellRendererText(),
-                text=0))
-        self._shortcut_treeview.append_column(
-            Gtk.TreeViewColumn(
-                # Translators: Column heading of the table listing the
-                # existing shortcuts
-                _('Shortcut expansion'),
-                Gtk.CellRendererText(),
-                text=1))
+        shortcut_treeview_column_0 = Gtk.TreeViewColumn(
+            # Translators: Column heading of the table listing the
+            # existing shortcuts
+            _('Shortcut'),
+            Gtk.CellRendererText(),
+            text=0)
+        shortcut_treeview_column_0.set_sort_column_id(0)
+        self._shortcut_treeview.append_column(shortcut_treeview_column_0)
+        shortcut_treeview_column_1 = Gtk.TreeViewColumn(
+            # Translators: Column heading of the table listing the
+            # existing shortcuts
+            _('Shortcut expansion'),
+            Gtk.CellRendererText(),
+            text=1)
+        shortcut_treeview_column_1.set_sort_column_id(1)
+        self._shortcut_treeview.append_column(shortcut_treeview_column_1)
         self._shortcut_treeview.get_selection().connect(
             'changed', self.on_shortcut_selected)
         self._shortcut_treeview_scroll.add(self._shortcut_treeview)
```

**Comment by psads-git** [comment]
I have already tried the new rpm and it is working perfectly: Now, the shortcuts fields can be sorted! Thanks, Mike!

**Comment by mike-fabian** [comment]
Thank you for testing!

Oh, I pasted the comment about the new build into the wrong issue:

https://github.com/mike-fabian/ibus-typing-booster/issues/158#issuecomment-798729522

**Comment by mike-fabian** [comment]
> I have already tried the new rpm and it is working perfectly: Now, the shortcuts fields can be sorted! Thanks, Mike!

I wonder whether I should do that to the columns in the keybindings tab as well.

The keybindings are already sorted alphabetically by command name, ascending.

But would it be useful to make the column heading there clickable as well to be able to reverse the sort  order?

And make the  column heading of the right column clickable as well, even though sorting the lists of keybindings seems not very useful, but just for consistency?

**Comment by mike-fabian** [comment]
I think I make both columns sortable there as well, it would be weird it they react to clicks in one place and not in another, wouldn't it?

**Comment by psads-git** [comment]
You are absolutely right, Mike!

**Comment by mike-fabian** [comment]
https://download.copr.fedorainfracloud.org/results/mfabian/ibus-typing-booster/fedora-33-x86_64/02074155-ibus-typing-booster/

Exactly same version number. But this new build also makes keybindings treeview sortable.

**Comment by psads-git** [comment]
Thanks, Mike. I have just tried it, but it seems not being working.

**Comment by mike-fabian** [comment]
You mean the keybindings cannot be sorted? Did you really update the rpm?

**Comment by psads-git** [comment]
Yes, Mike. I did

dnf downgrade ibus-typing-booster

and subsequently

dnf update.

**Comment by mike-fabian** [comment]
I am not sure whether that works because it has exactly the same version number. I guess you just got back what you had before from some cache.

Here you can see that the keybindings are sorted in descending order after clicking on the heading:

![Screenshot](https://user-images.githubusercontent.com/2330175/111064754-21263b00-84b6-11eb-9b1e-5f30dee5f882.png)

**Comment by psads-git** [comment]
It is working now, Mike! Thanks!
