### ISSUE TITLE
Make it possible to type digits into the preedit

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#164]
Please, do that, if it does not cause you too much trouble. :-)

**Comment by mike-fabian** [comment]
As I explained, it is possible already, you just have to remove *all* digits  from the key bindings.

Have you tried that already?

I will make it controllable more fine grained though that you do not have to remove *all* digits from the key bindings but can keep either the regular digit keys *or* those on the numeric key pad.

**Comment by psads-git** [comment]
I have already tried it. However, when I try to use the following shortcut

1a

it expands to 

1One artist

when it should have expanded to

One artist -- the number 1 remains.

**Comment by mike-fabian** [comment]
Works for me. See the keybindings settings and the shortcut definition and the correct expansion in this screenshot:

![Screenshot](https://user-images.githubusercontent.com/2330175/111065139-7cf1c380-84b8-11eb-8562-e7cd2f7d4c1f.png)

**Comment by psads-git** [comment]
It only occurs after committing, Mike!

**Comment by mike-fabian** [comment]
Not for me.

**Comment by mike-fabian** [comment]
Here in this video I do the first commit by typing Tab followed by space.

And the second commit by typing F1:

https://user-images.githubusercontent.com/2330175/111065810-ecb57d80-84bb-11eb-9750-1126ba7d301b.mp4

**Comment by psads-git** [comment]
In my case:

https://user-images.githubusercontent.com/75945439/111066284-14094c00-84b6-11eb-8f0d-f6764506030f.mp4

Moreover, the problem with newlines in Firefox and Thunderbird has returned!

**Comment by mike-fabian** [comment]
I can see in your video that the 1 does not go into the preedit, it is not underlined. 

So you probably have not removed all digits from the keybindings. 

Can you show me your keybinding settings either with a screenshot or by pasting the output of 

```
dconf dump /org/freedesktop/ibus/engine/typing-booster/
```

here?

**Comment by mike-fabian** [comment]
> Moreover, the problem with newlines in Firefox and Thunderbird has returned!

I guess you have reverted to an older version with your  

> dnf downgrade ibus-typing-booster
> 
> and subsequently
> 
> dnf update.

**Comment by psads-git** [comment]
> I can see in your video that the 1 does not go into the preedit, it is not underlined.
> 
> So you probably have not removed all digits from the keybindings.
> 
> Can you show me your keybinding settings either with a screenshot or by pasting the output of
> 
> ```
> dconf dump /org/freedesktop/ibus/engine/typing-booster/
> ```
> 
> here?

Thanks, Mike:

$ dconf dump /org/freedesktop/ibus/engine/typing-booster/
[/]
arrowkeysreopenpreedit=false
autocapitalize=false
autocommitcharacters=''
autoselectcandidate=false
dictionary='en_US,pt_PT'
emojipredictions=false
inlinecompletion=true
inputmethod='NoIME'
keybindings={'remove_candidate_6': <['Control+6', 'Control+KP_6', 'Control+F6']>, 'remove_candidate_1': <['Control+1', 'Control+KP_1', 'Control+F1']>, 'remove_candidate_2': <['Control+2', 'Control+KP_2', 'Control+F2']>, 'next_case_mode': <['Shift_L']>, 'next_input_method': <['Control+Down', 'Control+KP_Down']>, 'commit_candidate_5': <@as []>, 'lookup_table_page_up': <['Page_Up', 'KP_Page_Up', 'KP_Prior']>, 'previous_case_mode': <['Shift_R']>, 'setup': <['Mod5+F10']>, 'remove_candidate_8': <['Control+8', 'Control+KP_8', 'Control+F8']>, 'previous_input_method': <['Control+Up', 'Control+KP_Up']>, 'lookup_related': <['Mod5+F12']>, 'commit_candidate_6': <@as []>, 'remove_candidate_3': <['Control+3', 'Control+KP_3', 'Control+F3']>, 'select_next_candidate': <['Tab', 'ISO_Left_Tab', 'Down', 'KP_Down']>, 'remove_candidate_9': <['Control+9', 'Control+KP_9', 'Control+F9']>, 'commit_candidate_1': <@as []>, 'commit_candidate_7': <@as []>, 'next_dictionary': <['Mod1+Down', 'Mod1+KP_Down']>, 'remove_candidate_4': <['Control+4', 'Control+KP_4', 'Control+F4']>, 'toggle_input_mode_on_off': <@as []>, 'commit_candidate_2': <@as []>, 'speech_recognition': <@as []>, 'commit_candidate_8': <@as []>, 'lookup_table_page_down': <['Page_Down', 'KP_Page_Down', 'KP_Next']>, 'select_previous_candidate': <['Shift+Tab', 'Shift+ISO_Left_Tab', 'Up', 'KP_Up']>, 'remove_candidate_5': <['Control+5', 'Control+KP_5', 'Control+F5']>, 'toggle_emoji_prediction': <['Mod5+F6']>, 'toggle_hide_input': <['Shift+Control+Escape']>, 'commit_candidate_3': <@as []>, 'toggle_off_the_record': <['Mod5+F9']>, 'cancel': <['Escape']>, 'enable_lookup': <['Tab', 'ISO_Left_Tab']>, 'commit_candidate_9': <@as []>, 'previous_dictionary': <['Mod1+Up', 'Mod1+KP_Up']>, 'commit_candidate_1_plus_space': <['F1']>, 'commit_candidate_2_plus_space': <['KP_2', 'F2']>, 'commit_candidate_3_plus_space': <['KP_3', 'F3']>, 'commit_candidate_4': <@as []>, 'commit_candidate_5_plus_space': <['KP_5', 'F5']>, 'commit_candidate_6_plus_space': <['KP_6', 'F6']>, 'commit_candidate_7_plus_space': <['KP_7', 'F7']>, 'commit_candidate_8_plus_space': <['KP_8', 'F8']>, 'commit_candidate_9_plus_space': <['KP_9', 'F9']>, 'commit_candidate_4_plus_space': <['KP_4', 'F4']>, 'remove_candidate_7': <['Control+7', 'Control+KP_7', 'Control+F7']>}
mincharcomplete=1
offtherecord=false
qtimmoduleworkaround=true
tabenable=false
$

**Comment by psads-git** [comment]
> > Moreover, the problem with newlines in Firefox and Thunderbird has returned!
> 
> I guess you have reverted to an older version with your
> 
> > dnf downgrade ibus-typing-booster
> > and subsequently
> > dnf update.

I do not think so:

$ rpm -qa ibus-typing-booster
ibus-typing-booster-2.11.1-1.fc33.noarch
$

**Comment by mike-fabian** [comment]
```
'commit_candidate_2_plus_space': <['KP_2', 'F2']>
```
Your key bindings still contain digit keys. There is still KP_2. Unless you remove *all* digit keys 0, 1, ..., 9 *and* KP_0, KP_1, ..., KP9 from *all* key bindings, you cannot type digits into the preedit.

**Comment by mike-fabian** [comment]
I want to improve that by allowing entering digits into the preedit with one set and committing with the other.

I.e. you could remove 0,  1, ..., 9 and then type into the preedit with these and still use KP_0, KP1, ..., KP_9 to commit a candidate.

Or the other way round. 

But this is not implemented yet. With the current implementation, you have to remove *all* digit keys from the key bindings to be able to type digits into the preedit. Then you still have F1, ..., F9 available to commit candidates.

**Comment by psads-git** [comment]
> ```
> 'commit_candidate_2_plus_space': <['KP_2', 'F2']>
> ```
> 
> Your key bindings still contain digit keys. There is still KP_2. Unless you remove _all_ digit keys 0, 1, ..., 9 _and_ KP_0, KP_1, ..., KP9 from _all_ key bindings, you cannot type digits into the preedit.

I have removed all numbers from keybindings (I guess it is not needed to remove Control+KPX):

------------------------------
$ dconf dump /org/freedesktop/ibus/engine/typing-booster/
[/]
arrowkeysreopenpreedit=false
autocapitalize=false
autocommitcharacters=''
autoselectcandidate=false
dictionary='en_US,pt_PT'
emojipredictions=false
inlinecompletion=true
inputmethod='NoIME'
keybindings={'remove_candidate_6': <['Control+6', 'Control+KP_6', 'Control+F6']>, 'remove_candidate_1': <['Control+1', 'Control+KP_1', 'Control+F1']>, 'remove_candidate_2': <['Control+2', 'Control+KP_2', 'Control+F2']>, 'next_case_mode': <['Shift_L']>, 'next_input_method': <['Control+Down', 'Control+KP_Down']>, 'commit_candidate_5': <@as []>, 'lookup_table_page_up': <['Page_Up', 'KP_Page_Up', 'KP_Prior']>, 'previous_case_mode': <['Shift_R']>, 'setup': <['Mod5+F10']>, 'remove_candidate_8': <['Control+8', 'Control+KP_8', 'Control+F8']>, 'previous_input_method': <['Control+Up', 'Control+KP_Up']>, 'lookup_related': <['Mod5+F12']>, 'commit_candidate_6': <@as []>, 'remove_candidate_3': <['Control+3', 'Control+KP_3', 'Control+F3']>, 'select_next_candidate': <['Tab', 'ISO_Left_Tab', 'Down', 'KP_Down']>, 'remove_candidate_9': <['Control+9', 'Control+KP_9', 'Control+F9']>, 'commit_candidate_1': <@as []>, 'commit_candidate_7': <@as []>, 'next_dictionary': <['Mod1+Down', 'Mod1+KP_Down']>, 'remove_candidate_4': <['Control+4', 'Control+KP_4', 'Control+F4']>, 'toggle_input_mode_on_off': <@as []>, 'commit_candidate_2': <@as []>, 'speech_recognition': <@as []>, 'commit_candidate_8': <@as []>, 'lookup_table_page_down': <['Page_Down', 'KP_Page_Down', 'KP_Next']>, 'select_previous_candidate': <['Shift+Tab', 'Shift+ISO_Left_Tab', 'Up', 'KP_Up']>, 'remove_candidate_5': <['Control+5', 'Control+KP_5', 'Control+F5']>, 'toggle_emoji_prediction': <['Mod5+F6']>, 'toggle_hide_input': <['Shift+Control+Escape']>, 'commit_candidate_3': <@as []>, 'toggle_off_the_record': <['Mod5+F9']>, 'cancel': <['Escape']>, 'enable_lookup': <['Tab', 'ISO_Left_Tab']>, 'commit_candidate_9': <@as []>, 'previous_dictionary': <['Mod1+Up', 'Mod1+KP_Up']>, 'commit_candidate_1_plus_space': <['F1']>, 'commit_candidate_2_plus_space': <['F2']>, 'commit_candidate_3_plus_space': <['F3']>, 'commit_candidate_4': <@as []>, 'commit_candidate_5_plus_space': <['F5']>, 'commit_candidate_6_plus_space': <['F6']>, 'commit_candidate_7_plus_space': <['F7']>, 'commit_candidate_8_plus_space': <['F8']>, 'commit_candidate_9_plus_space': <['F9']>, 'commit_candidate_4_plus_space': <['F4']>, 'remove_candidate_7': <['Control+7', 'Control+KP_7', 'Control+F7']>}
mincharcomplete=1
offtherecord=false
qtimmoduleworkaround=true
tabenable=false
$ 
------------------------------

but now "1a" does not expand to the desired expansion.

**Comment by mike-fabian** [comment]
> (I guess it is not needed to remove Control+KPX):

You can keep Control+1 and Control+KP_1, etc... that doesn’t matter.

**Comment by mike-fabian** [comment]
> but now "1a" does not expand to the desired expansion.

So you can type 1 into the preedit now, right?

And what does 1a expand to? How have you defined the expansion? Does it look different than in my screenshot and video above? (My screenshot and video show also the part of the setup tool which shows the “1a -> one artist” expansion.

**Comment by psads-git** [comment]
Please, see what happens, Mike:

https://user-images.githubusercontent.com/75945439/111067823-d8728000-84bd-11eb-83ac-1d001a7b12c0.mp4

**Comment by mike-fabian** [comment]
OK, now you can type the 1 into the preedit. Good. 

Are you sure you defined the expansion correctly?

**Comment by psads-git** [comment]
That is working now, Mike! I redefined the expansion.

**Comment by mike-fabian** [comment]
OK, so basically it works. 

I have a new change to make it possible to keep one set of digit keys in  the keybindings and keep the other to 
type numbers into the preedit.

**Comment by psads-git** [comment]
OK, Mike, but take your time -- that is not urgent.

**Comment by mike-fabian** [comment]
That change achieves the following:

Before, if any digits, whether normal digits or from the numeric keypad, were used in any keybinding, one could not type them into the preedit.  Usually these are bound to functions to commit candidates, either they can commit candidates or produce input into the preedit, not both at the same time.

I.e. such digits are used to commit candidates, they cannot produce input into the preedit. Therefore, in order to make it still possible to type digits at all, digits were committed directly (possibly transliterated) if typed while the preedit was still empty.

This improvement gives more fine grained control, now one can for example only remove all the regular digits 0, 1, ..., 9 from the key bindings and leave the keypad digits in the key bindings. Then, one can type numbers into the preedit using regular digits 0, 1, ..., 9 but one can still commit for example candidate number one using KP_1. And if KP_1 is typed while the preedit is empty, it is directly committed (possibly transliterated).

Or the other way round: One can remove only the keypad digits KP_0, KP_1, ..., KP_9 from thekeybindings and leave the regular digits there. Then one can type numbers into the preedit using the keypad digits but can commit for example candidate one by typing the normal 1. And if the normal 1 is typed while the preedit is empty, it is directly committed (possibly transliterated).

**Comment by mike-fabian** [comment]
A new build is running, I increased the version number to 2.11.2 in order not to confuse dnf when upgrading.

The 2.11.2 build should have the change which allows to use one set of digit keys to type numbers into the preedit and the other set to commit candidates.

**Comment by mike-fabian** [comment]
One moment, I have a problem with a test case, the new build will take a bit longer.

**Comment by psads-git** [comment]
No problem, Mike!

**Comment by mike-fabian** [comment]
> Moreover, the problem with newlines in Firefox and Thunderbird has returned!

What about that? Was that just a glitch of the update? Accidentally tested with downgraded version I guess?

It still works fine for me.

**Comment by mike-fabian** [comment]
New build of 2.11.2 is ready:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/build/2074616/

Now you can leave one set of digits in the keybindings, eihter 1,..., 9 *or* KP_1, ..., KP9.

And use the one in the keybindings to commit candidates and the other set to enter numbers into the preedit.

**Comment by psads-git** [comment]
> > Moreover, the problem with newlines in Firefox and Thunderbird has returned!
> 
> What about that? Was that just a glitch of the update? Accidentally tested with downgraded version I guess?
> 
> It still works fine for me.

Just tried with the new version of ibus-typing-booster in Thunderbird:

https://user-images.githubusercontent.com/75945439/111073254-f815a280-84d5-11eb-811a-c83bb608a8d9.mp4

**Comment by mike-fabian** [comment]
And is that OK or not? How many new lines should there be in your expansion?

**Comment by psads-git** [comment]
> New build of 2.11.2 is ready:
> 
> https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/build/2074616/
> 
> Now you can leave one set of digits in the keybindings, eihter 1,..., 9 _or_ KP_1, ..., KP9.
> 
> And use the one in the keybindings to commit candidates and the other set to enter numbers into the preedit.

Thanks, Mike! Now, it works perfectly with only one of numeric keybindings set.

**Comment by psads-git** [comment]
> And is that OK or not? How many new lines should there be in your expansion?

It is a bit annoying, but it is OK and nothing serious. All newlines between written lines get deleted during the expansion -- even 10 newlines! :-)

**Comment by mike-fabian** [comment]
Weird, for me that works when writing a mail with Gmail in Firefox (I didn’t test Thunderbird).

**Comment by psads-git** [comment]
In GMail/Firefox, the newlines are converted to white spaces! ;-)

**Comment by mike-fabian** [comment]
For me I had the problem only when I committed  the new lines as '\n' inside the strings. And it was fixed after forwarding a Return key event for every new line with a 100ms sleep after each line. 

I didn’t do any  changes to that part of the code after you said it worked.

**Comment by mike-fabian** [comment]
the length of the sleep is set here:

https://github.com/mike-fabian/ibus-typing-booster/blob/master/engine/hunspell_table.py#L143

You could try to edit that line (as super user) to change the length of the sleep and restart ibus (or restart your XFCE session) to test whether a different length of sleep after each line would change anything. This is the file you would need to edit:

/usr/share/ibus-typing-booster/engine/hunspell_table.py

**Comment by mike-fabian** [comment]
Maybe you did check the option: “Use a workaround for a bug in Qt im module”?

If you check that option, forward key event is avoided and the whole expansion is committed as one string.

> In GMail/Firefox, the newlines are converted to white spaces! ;-)

If I have the option “Use a workaround for a bug in Qt im module”, then this happens for me in Gmail in firefox as well.

So don’t use that option if you don’t have to. It is only for some versions of Qt and for Wayland.

**Comment by psads-git** [comment]
Yes, Mike, turning off that option solves the problem. Thanks, Mike, once again!

**Comment by mike-fabian** [comment]
> Yes, Mike, turning off that option solves the problem. Thanks, Mike, once again!

That option should be used only when absolutely needed. If possible don’t use it.

**Comment by mike-fabian** [comment]
I Wayland you have to use that option at the moment or type space twice after each word. I hope I can find a better workaround for Wayland when I am back in April. Using that option is really not good, only a last resort.

**Comment by psads-git** [comment]
OK, Mike, I understand that.
