### ISSUE TITLE
Don't hardcode icon name on desktop file

### ISSUE THREAD

**Issue by bilelmoussaoui** [mike-fabian/ibus-typing-booster#17]
Desktop files uses a hardcoded icon name, which means that no icon theme can provide an icon for the emoji-icon-picker or whatever desktop file is shipped by default with the application.
https://github.com/mike-fabian/ibus-typing-booster/blob/master/engine/emoji-picker.desktop.in.in#L5
https://github.com/mike-fabian/ibus-typing-booster/blob/master/setup/ibus-setup-typing-booster.desktop.in.in#L5

Both desktop files, should be modified to use `Icon=ibus-hunspell-table` and copy the icons to `/usr/share/icons/hicolor/` instead of hardcoding them somewhere else.

I can open a PR if you wish :)

Thanks!

**Comment by mike-fabian** [comment]
Yes, a pull request would be nice!

**Comment by bil-elmoussaoui** [comment]
I will create a PR this evening
