### ISSUE TITLE
Arrow left fails to reopen the first preedit correctly, subsequent ones work

### ISSUE THREAD

**Issue by mike-fabian** [mike-fabian/ibus-typing-booster#196]
Tested on Fedora 34 in gedit on a i3 desktop.

The problem occurs only with arrow left, not with backspace. See this video:

https://user-images.githubusercontent.com/2330175/128041079-2d97a2f0-5b0f-4e9f-832a-0c9f0fe60ced.mp4

**Comment by mike-fabian** [comment]
As seen in the video, when I type 

“a b c d e Left"

the “e” is deleted. Continuing to type left reopens the preedits for a, b, c, and d correctly without deleting.

When using Backspace however, i.e. 

“a b c d e Backspace”

there is no such problem.

**Comment by psads-git** [comment]
Thanks, Mike! This bug makes ibus-typing-booster simply not usable: Several words are deleted when one uses the left arrow and edits previous committed words.  So, it appears, that the best is to switch off "Arrow keys can reopen a preedit".

**Comment by mike-fabian** [comment]
> Thanks, Mike! This bug makes ibus-typing-booster simply not usable: Several words are deleted when one uses the left arrow and edits previously committed words. So, it appears, that the best is to switch off "Arrow keys can reopen a preedit".

That is the reason why this option was off by default! It was just too unreliable.

I just finished rewriting the reopening of the preedit completely, I think it works **much** better now. 
I’ll upload a test version to copr in about  half an hour ⏳

**Comment by psads-git** [comment]
Thanks, Mike! I am now going for a walk, but, as soon as I am back, I shall test the new version.

**Comment by mike-fabian** [comment]
Sorry, the build I made works, but only if the debug level is > 1.

Fixing this, but maybe tomorrow, it is already 1 am in my timezone.

**Comment by psads-git** [comment]
No, problem, Mike! In my timezone, it is still 12:00 AM.

**Comment by mike-fabian** [comment]
The build which finished about 20 minutes ago should work also with debug level 0.

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/

ibus-typing-booster-2.13.3

**Comment by psads-git** [comment]
Thanks, Mike! Please, go to bed to sleep! :-)

**Comment by mike-fabian** [comment]
😴

**Comment by mike-fabian** [comment]
It seems to work much better now. In this video I use the arrow keys, the Backspace and the Delete key.

All of them reopen the preedit “most of the time” correctly, nothing is deleted and no junk is inserted.

Sometimes when typing rather fast, for example when the cursor is behind “is” in “is a” and one types Right, Left, Right, Left in quick succession, the preedit is sometimes not reopened because my new code detects that something has gone wrong in updating the surrounding text. Either the surrounding text has not been updated at all or it contains something which looks wrong.  Reopening  the preedit when the surrounding text does not agree with what is really there in the editor would create a mess, so I just don’t do it if it looks like I cannot trust the surrounding text.

As the updating of the surrounding text is an asynchronous process, how often reopening the preedit fails depends on the speed of the computer and the systemload. When I test this on bare metal, it works quite well, 95% of the time the preedits are reopened when  they should. But when I test in a virtual machine the preedits fail to reopen much more often, I have to type really slow  to see preedits reopen at all in my f34 virtual machine. But it is still better to not reopen at all then to reopen wrongly.

https://user-images.githubusercontent.com/2330175/128489490-87e2d080-87b1-4ce5-bafc-43fea0103e25.mp4

**Comment by mike-fabian** [comment]
I uploaded a 2.13.4 build to 

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/

which also has the improvement for https://github.com/mike-fabian/ibus-typing-booster/issues/198

**Comment by psads-git** [comment]
I hope you had a good night of sleep, in spite of the fact you went very late to bed, Mike! Programming is too mind-absorbing and kills our sleep... ;-)

There is still a bug left. Please, see the attached video. The bug is caused when after pressing END one presses RIGHT ARROW.

Moreover, if one goes back to near the beginning of a long phrase to re-edit some word, one has no fast way to go to the end of the phrase -- the END key does not do that.

https://user-images.githubusercontent.com/75945439/128507586-e355dd9f-268b-48f3-bdde-011a3c6eac87.mp4

**Comment by mike-fabian** [comment]
Ibus-typing-booster does not handle neither the End nor the Home key yet. Not **at** **all**.
It never did handle these keys, I just didn't think about these and so far nobody complained.

**Comment by mike-fabian** [comment]
It would be nice if you keep using ibus-typing-booster with the option “Arrow keys can reopen preedit” always on and report if that causes any problems.

It seems to be much better now then with the old implemention. Sometimes it fails to reopen preedits, but then it does just nothing and doesn’t cause any harm. 

If that is really try and having that option on never causes any harm, I would like to turn it on by default in a future release.

And rename it to something like:

   [✓] Enable reopening preedit

or:

   [✓] Enable reopening preedit on cursor movements

(The shorter name is probably better).

I would like to change the name because it does not only affect the arrow keys, also BackSpace and Delete keys may reopen a preedit. Currently repositioning with the mouse never reopens a preedit, but I might implement that in future. Having “Arrow keys” in the name of that option is already wrong now and maybe be even more wrong in future if I implement this when repositioning with the mouse.

So it would really be nice if you report whether having that option on causes some problems which would not occur when that option is off.

**Comment by psads-git** [comment]
Hi, Mike,

Yesterday afternoon, I was away from the computer. So, I am replying only now.

Surely, I will continue to test the new version and I will report to you anything that may go wrong. This reopening preedit enhancement really improves the ibus-typing-booster users benefit. 

It seems that the shorter name for the option is the best. 

The interaction with ibus-typing-booster is mainly done through keyboard. So, it is no really important that the mouse never reopens a preedit -- that is a secondary goal.

Have a nice Sunday!

**Comment by mike-fabian** [comment]
A new test version 2.13.7 is available at:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/ 

It contains these improvements over the last version you tested:

- Translation update from Weblate (de, nl, pl, sv, tr, uk updated to 100%)
- Show possible compose completions on request (Resolves: https://github.com/mike-fabian/ibus-typing-booster/issues/208)
- When setting self._input_mode to False (direct input), set self._hide_input to False as well
- Never mix context from surrounding text with remembered context (Resolves: https://github.com/mike-fabian/ibus-typing-booster/issues/204)
- Rename the option “Use a workaround for a bug in Qt im module” to “Avoid using the forward_key_event() function” (Resolves: https://github.com/mike-fabian/ibus-typing-booster/issues/200)

Implementing showing the possible completions of compose sequences required quite a lot of changes, I hope I didn’t break anything.

Even if you don’t need compose at all, it would still be nice to test this version to see if everything else continues to function normally.

**Comment by psads-git** [comment]
Thanks, Mike. I have already installed the latest version, which I will be using everyday from now on. If I find any issue, I will report to you immediately.

**Comment by mike-fabian** [comment]
By the way, what language(s) are you typing with ibus-typing-booster? Only English? Portuguese? Something else?

**Comment by psads-git** [comment]
I am from Portugal and therefore I use Portuguese a lot! However, I also use English very often.

**Comment by psads-git** [comment]
With ibus-typing-booster on, SHIFT+ARROWS do not select text, Mike!

**Comment by mike-fabian** [comment]
> With ibus-typing-booster on, SHIFT+ARROWS do not select text, Mike!

I cannot reproduce this. How to reproduce this exactly? Maybe video?

**Comment by mike-fabian** [comment]
It seems to select fine for me: 

https://user-images.githubusercontent.com/2330175/128779503-73ba1e41-d9cc-4866-aa6e-69da73bb3107.mp4

**Comment by psads-git** [comment]
Thanks, Mike. That only occurs while the word is underlined (in the example of the video below, the word tomorrow). 

https://user-images.githubusercontent.com/75945439/128857987-e2bb2ee7-893e-49e4-810e-23064bdd82fa.mp4

**Comment by mike-fabian** [comment]
So it is not when ibus-typing-booster is just “on”, it is when there is something in the preedit (that is the underlined part).

**Comment by psads-git** [comment]
You are right, Mike. My fault.

**Comment by mike-fabian** [comment]
This is kind of a new feature, wasn't broken recently but never worked so far. 

I created a new issue for this: 

https://github.com/mike-fabian/ibus-typing-booster/issues/210
