### ISSUE TITLE
ibus-typing-booster should handle the End, Home, KP_End, KP_Home keys reasonably.

### ISSUE THREAD

**Issue by mike-fabian** [mike-fabian/ibus-typing-booster#199]
Until know, bus-typing-booster does  not handle the End, Home, KP_End, KP_Home at all.

That causes  problems when these keys are pressed while a preedit is open. 

See also:

https://github.com/mike-fabian/ibus-typing-booster/issues/196#issuecomment-894212827

**Comment by psads-git** [comment]
Thanks, Mike!

**Comment by mike-fabian** [comment]
New build 2.13.5 is here which should fix this:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/

It would be nice if you could test it.

**Comment by mike-fabian** [comment]
This was very easy to fix, with the fix applied it works like this:


https://user-images.githubusercontent.com/2330175/128523503-c3e25316-d178-440d-a35c-d9db22a8953c.mp4

**Comment by mike-fabian** [comment]
In the video I type the word “test” in the middle of the line, then type End or Home and “test” is committed and the cursor jumps to the end or the beginning of the line.

I can also first accept the suggestion “testing” by typing Tab and then type End or Home. Then the word “testing” is committed and the cursor jumps to the beginning or the end of the line.

**Comment by psads-git** [comment]
Thanks, Mike! From what I already tested, it seems to be working perfectly. But, since I use ibus-typing-booster on a daily basis, if I find some issue, I will straightway report that to you.

**Comment by mike-fabian** [comment]
> Thanks, Mike! From what I already tested, it seems to be working perfectly. But, since I use ibus-typing-booster on a daily basis, if I find some issue, I will straightway report that to you.

Great, thank you!
