### ISSUE TITLE
Latin-Pre and Latin-Post do not work at all

### ISSUE THREAD

**Issue by PedroArvela** [mike-fabian/ibus-typing-booster#21]
Fedora 25 with Plasma 5 Desktop. IBus 1.5.14 and IBus Typing Booster 1.5.25

Using US keyboard and "US International with dead keys" layout when not using Typing Booster

**Steps to reproduce:**

1. Enable any language with Typing Booster, i.e. "Portuguese - PT (Typing Booster)"
2. Attempt to write words which require diacritics (i.e. olá or cão), using any of the input methods:
   * Direct Input (US-intl w/ dead keys): ol'a c~ao
   * Latin-Pre: ol'a c~ao
   * Latin-Post: ola' ca~o

**Expected results:**

The words "olá cão".

**Actual results:**

The words "ola cao".

**Aditional notes:**

Applies to any kinds of apps, both GTK, Qt or pure XIM apps (such as rxvt-unicode). Both with the Qt workaround enabled or disabled.

Even using the Portuguese Layout and typing the key which would give the proper accent does not make the preedit have any accented letter, neither in Latin-Pre, Latin-Post or Direct Input.

**Comment by PedroArvela** [comment]
I'm sorry, I've tested now with US normal instead of US international and Latin-Pre does work in this situation.

I'm closing the bug as the problem is from the wrong underlying layout being used.

**Comment by mike-fabian** [comment]
By the way, the problem you had with the "US International with dead keys"  keyboard layout is fixed now in ibus-typing-booster 2.7.0. Dead keys and other compose sequences are now supported.
