### ISSUE TITLE
The behaviour of Shift+<arrow-key>while a preëdit  open should be improved

### ISSUE THREAD

**Issue by mike-fabian** [mike-fabian/ibus-typing-booster#210]

**Comment by mike-fabian** [comment]
Shift + arrow key (Left, KP_Left, Right, KP_Right, Up, KP_UP, Down, KP_Down) typed while a preedit is open should do this to improve the behaviour:

- commit the preëdit. Now the cursor is at the right end of the text just committed
- Forward a suitable number of Left key events (without Shift) using forward_key_event() to move the cursor back to the position in the text where it was before the commit
- Sleep about 0.1 seconds to  give the cursor time to arrive.  Now forward the original key event which triggered the commit.

**Comment by mike-fabian** [comment]
**Maybe** no sleep is needed, let’s try and see...

**Comment by mike-fabian** [comment]
Actually it is not only Shift + arrow key (Left, KP_Left, Right, KP_Right, Up, KP_UP, Down, KP_Down) but

Shift and any of these:

IBus.KEY_Right, IBus.KEY_KP_Right,
IBus.KEY_Left, IBus.KEY_KP_Left,
IBus.KEY_End, IBus.KEY_KP_End,
IBus.KEY_Home, IBus.KEY_KP_Home,
IBus.KEY_Down, IBus.KEY_KP_Down,
IBus.KEY_Up, IBus.KEY_KP_Up,
IBus.KEY_Page_Down,
IBus.KEY_KP_Page_Down,
IBus.KEY_KP_Next,
IBus.KEY_Page_Up,
IBus.KEY_KP_Page_Up,
IBus.KEY_KP_Prior

**Comment by psads-git** [comment]
Thanks, Mike!

**Comment by mike-fabian** [comment]
https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/ has a 2.13.9 build now which should work better.

**Comment by mike-fabian** [comment]
https://user-images.githubusercontent.com/2330175/128908539-b2772c85-a4c5-4bdb-8432-41c99e3202f5.mp4

**Comment by mike-fabian** [comment]
**Preparation**: In the second line, I type the word "test", see the suggestion "testing", type Left twice. The cursor is not behind "te" and the preedit is still open.

Then I type:

- Shift+Left Left Left ...

  repeat **preparation**
  
- Shift+Home

  repeat **preparation**
  
- Shift+Up

  repeat **preparation**
  
- Shift+Page_Down

Behaves much better now, I think.

**Comment by psads-git** [comment]
Apparently, this new version does not solve the problem. Please, see the attached video: I cannot highlight "test" with SHIFT+LEFT

https://user-images.githubusercontent.com/75945439/128912129-e05c2017-9ea4-40b3-9ef5-08c161aa28a4.mp4

**Comment by mike-fabian** [comment]
Hm, weird, exactly the same works fine for me:


Uploading Peek 2021-08-10 20-41.mp4…

**Comment by mike-fabian** [comment]
I typed 

"This is a test." and then Shift+Left 9 times.

Did you do anything different?

**Comment by mike-fabian** [comment]
I tried with and without NumLock, it didn't matter.

**Comment by psads-git** [comment]
Thanks, Mike! I did as you did. Maybe your ibus-typing-booster configuration does not match mine. Please, see my configuration:

![Screenshot_2021-08-10_20-16-25](https://user-images.githubusercontent.com/75945439/128921614-25d223cd-294d-44f8-8a27-d86e8f3700df.png)

**Comment by mike-fabian** [comment]
Your configuration looks fine, it should not matter.

**Comment by mike-fabian** [comment]
You really have 2.13.9 now?

There is an "About" button in the setup tool which shows the version.

Did you remember to restart your session (When using Gnome)? When not using Gnome, you can also type "ibus restart" in a terminal.

**Comment by psads-git** [comment]
I had 2.13.8. The 2.13.9 only now reached the updates!

With 2.13.9, it works fine, without the reported issue. Sorry for not having noticed that `dnf update` did not update the last version, but the previous one. I should have done `dnf clean all` first. Again, sorry for the inconvenience.

**Comment by mike-fabian** [comment]
Great that it works, I found it quite confusing to implement 🤯.

**Comment by psads-git** [comment]
I imagine that it is confusing, because of the numerous possible cases that one must take into consideration. 

The fact that the surrounding text was not working properly, because of a third party software, shows that this sort of programs are complicate to develop.

**Comment by mike-fabian** [comment]
Yes, there are many possible keys to press together with shift, it makes a difference whether the cursor is at the beginning or the end of the preëdit or somewhere in the middle, it also makes a difference whether suggestions are just shown or whether one suggestion is selected when such a key is pressed.

**Comment by mike-fabian** [comment]
Surrounding text is still very problematic, especially under Wayland it seems to work almost never. I do lots of sanity checks now and if anything looks not right, I don't use surrounding text, that is still better than to delete some text which shouldn't have been deleted or insert some junk. On Wayland, when I watch what happens in debug.log while trying to use surrounding text, I see almost always that surrounding text use was avoided because the results obtained from surrounding text didn't pass my sanity tests. I need to investigate that in detail and probably report some bugs.

**Comment by psads-git** [comment]
Surrounding text is buggy because is too complicated to program. And also maybe because very few people complain!
