### ISSUE TITLE
ibus does change passwords when typing

### ISSUE THREAD

**Issue by jjb11** [mike-fabian/ibus-typing-booster#24]
ibus does interfere with keyboard shortcuts. and with typing passwords.

**Comment by mike-fabian** [comment]
Where does it interfere with passwords? In terminals, the input method has no way to know whether a password is typed or not. I.e. in terminals, *all* input methods show the passwords while typing and may interfere with typing the passwords when the  input is changed by the input method. In password entry fields displayed by desktops like Gnome, this should not happen though, input  methods including ibus-typing-booster should be disabled on password input fields.

**Comment by mike-fabian** [comment]
No details given after several month,  I am closing this.
