### ISSUE TITLE
Feature request: LaTeX commands in emoji search

### ISSUE THREAD

**Issue by gjvnq** [mike-fabian/ibus-typing-booster#248]
It would be pretty beneficial to be able to type `<emoji> <\> <i> <i> <n> <t> <space>` to get ∬ instead of `<emoji> <i> <n> <t> <e> <g> <r> <a> <l> <space> <space> <right arrow> <enter>`.

There is a good list of which LaTeX commands to Unicode code points from the [unicode-math](https://ctan.dcc.uchile.cl/macros/unicodetex/latex/unicode-math/unimath-symbols.pdf) package: https://ctan.dcc.uchile.cl/macros/unicodetex/latex/unicode-math/unicode-math-table.tex

**Comment by mike-fabian** [comment]
The file `/usr/share/m17n/math-latex.mim` contains the sequences currently defined. You can also display that file using the setup tool:


https://user-images.githubusercontent.com/2330175/137861491-0e5fd248-2235-4a91-a1e4-c7a1e1982787.mp4

**Comment by gjvnq** [comment]
I had tried but it wasn't working. I then did a quick look into the source and found very little mentioning latex and came to the wrong conclusion that the feature wasn't implemented instead of it just being a problem on my machine.
