### ISSUE TITLE
Does not show up in Add Input Method

### ISSUE THREAD

**Issue by tastytea** [mike-fabian/ibus-typing-booster#249]
I'm trying to configure ibus-typing-booster 2.14.13 with ibus 1.5.22 using “[When using other desktops than Gnome3](https://mike-fabian.github.io/ibus-typing-booster/docs/user/#1_3)” from the documentation. When I try to add the input method in `ibus-setup`, “Typing Booster” does not show up and there is no “Other” (or “Sonstige” in my case) category.

I installed ibus and ibus-typing-booster via the Gentoo package manager. Python version is 3.9. The daemon is started with `ibus-daemon -drx`. I have restarted the daemon and even the whole computer.

![Screenshot of the add input method dialog](https://user-images.githubusercontent.com/3681516/137914103-89d28c93-9a58-4e32-9a1b-030f4646a75b.png)

**Comment by mike-fabian** [comment]
> `/usr/share/ibus/component/typing-booster.xml` exists and is exactly the same. `/usr/libexec/ibus-engine-typing-booster --xml` tries to invoke `/usr/bin/sh` (should be `/bin/sh`). When I fixed that, it printed the same as above.

If it does not print this output, it is not surprising that `ibus list-engine` does not list it.

> I have symlinked `/bin/sh` to `/usr/bin/sh` and restarted the daemon, but that made no difference.

But now that you have fixed it by doing that symlink, `/usr/libexec/ibus-engine-typing-booster --xml` prints the expected output and that should make ibus list it.

After restarting the daemon of course, but you say you did that.

I wonder whether I should install Gentoo in a vm and check myself ...
