### ISSUE TITLE
Feature Request: Preedit by hotkey

### ISSUE THREAD

**Issue by wyqydsyq** [mike-fabian/ibus-typing-booster#25]
The ideal behaviour from this project for me is for the preedit mode to only be enabled by a hotkey.

For example, the preedit mode being enabled by default prevents any autocompletions in my fish shell, suggestions in Google search results, or progressive search results as I type in Gnome Shell's Overview, until I commit the preedit text at which point the underlying application receives it.

Ideally I would like to be able to use my keyboard as normal with a vanilla input source, only engaging the `ibus-typing-booster` preedit mode and suggestions upon pressing a hotkey (e.g. Ctrl+Space). This would allow me to work like normal while also using this booster when I actually want to use it; inputting emojis and special characters, in a more user-friendly manner than using the Compose Key.

I'm aware that a similar behaviour to what I'm asking for can be achieved by switching between this booster and my original input source, but it would be preferable to avoid having duplicated input sources (two for EN_AU, the original and this booster one) and seeing the input menu in my top bar (usually doesn't show up as I only have one language)

**Comment by mike-fabian** [comment]
Fixed in https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.4.1
