### ISSUE TITLE
Passwords are visible while typing in terminal emulators

### ISSUE THREAD

**Issue by wyqydsyq** [mike-fabian/ibus-typing-booster#26]
## Steps to reproduce:
 - Install and configure `ibus-typing-booster` in Gnome 3
 - Open Tilix
 - Run a command where you have to authenticate as root (e.g. `sudo touch hello.txt`)
 - Shit your pants when you realize anyone looking over your shoulder would have just seen your root password typed out

`ibus-typing-booster` seems to enter a preedit mode by default when typing, and cannot detect if a terminal emulator is asking for a password, so will show the password in the preedit mode as it is typed.

**Comment by mike-fabian** [comment]
In terminals, the input method has no way to know whether a password is typed or not. I.e. in terminals, all input methods, not only ibus-typing-booster, show the passwords while typing and may interfere with typing the passwords when the input is changed by the input method. In password entry fields displayed by desktops like Gnome, this should not happen though, input methods including ibus-typing-booster should be disabled on such password input fields.

This is the same with any input method, for example a Japanese  input method like  ibus-kkc behaves the same way. As there seems to be no way for detecting whether a password is asked in a terminal emulator, there seems to be  no way to fix this.

**Comment by rugk** [comment]
Maybe it would be great if we could exclude the terminal to prevent this from happening: https://github.com/mike-fabian/ibus-typing-booster/issues/34
