### ISSUE TITLE
The space between punctuation and a word is not deleted on Web WhatsApp

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#261]
Please, Mike, see the video: The space between the first `ok` and `,` is not deleted. I am using Chrome.

https://user-images.githubusercontent.com/75945439/144693180-bab44605-5708-415a-b766-eb54ae1a61cb.mp4

**Comment by mike-fabian** [comment]
Another surrounding text problem.

Chrome does not support delete  surrounding text.

**Comment by mike-fabian** [comment]
https://github.com/keymanapp/keyman/issues/5510

**Comment by mike-fabian** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1123174

**Comment by mike-fabian** [comment]
I cannot do anything about this.

Maybe use Firefox for this.

**Comment by psads-git** [comment]
Thanks, Mike, I can confirm that, with Firefox, the reported problem does not occur.

**Comment by mike-fabian** [comment]
Maybe add a comment on the upstream chromium issue.

**Comment by psads-git** [comment]
Yes, Mike, I can do that. But what should I write there?

**Comment by mike-fabian** [comment]
That you would appreciate it if Chrome fixed their surrounding text support.

Maybe it helps if they see that many users are interested in that.

**Comment by mike-fabian** [comment]
This has also been reported in the ibus isssue tracker: https://github.com/ibus/ibus/issues/2354

(But it is a problem in chromium).

**Comment by psads-git** [comment]
Thanks, Mike. I have done so:

https://bugs.chromium.org/p/chromium/issues/detail?id=1123174#c12

**Comment by mike-fabian** [comment]
Thank you!
