### ISSUE TITLE
Provide an option to never show the suggestion balloon window

### ISSUE THREAD

**Issue by janvlug** [mike-fabian/ibus-typing-booster#266]
I would like to be able to use the ibus-typing-booster completely without the balloon. Could you add an option to never show the balloon window?

The only thing that I want is the inline suggestions to speed up my typing of long words.

**Comment by mike-fabian** [comment]
I made it now possible to use inline completion without automatic fallback to a candidate list

Now the inline completion option has 3 values:

- No
- Yes, with fallback to popup
- Yes, without fallback to popup

Even when “Yes, without fallback to popup” is chosen, it is still
possible to explicitly request a lookup table by typing the key bound
to the command `select_next_candidate` (By default this is the Tab
key). But fallback candidate lists are then shown only on request,
never automatically.

**Comment by mike-fabian** [comment]
Test builds of ibus-typing-booster-2.15.28 with the new feature for Fedora 34/35/36/rawhide are here:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/

If the option “inline completion” was on (checked) before the update, it will be reset to “No” after the update so you have to switch it on again. 

I think the new option “Yes, without fallback to popup” is what you want.

Can you please test this?

**Comment by mike-fabian** [comment]
Included in 2.16.0: https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.16.0
