### ISSUE TITLE
“Automatically select the best candidate” could be improved

### ISSUE THREAD

**Issue by mike-fabian** [mike-fabian/ibus-typing-booster#285]
Currently there is the option:

```
☑️ Automatically select the best candidate
```

which I personnally find almost useless (but I think there was at least one user who liked it, so I won’t take it away.

But it might be a good idea to add another level to that option instead of just **on** and **off**, maybe like this:

```
Automatically select the best candidate [Never|For very good candidates|Always]
```

**Never** would be the same as if the currently available option is **off**.

**Always** would be the same as if the currently available option is switched **on**.

**For very good candidates** would automatically select only in such cases where we have “almost full certainty”.

See also the discussion here:

https://github.com/mike-fabian/ibus-typing-booster/issues/158#issuecomment-1055100520

**Comment by psads-git** [comment]
Thanks, Mike! And have a good vacation!

**Comment by mike-fabian** [comment]
https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/

has new test builds ibus-typing-booster-2.16.9  

with an improved autoselection feature.
The option has three possible values now:

Automatically select the best candidate:  [ No | Yes, but only when extremely likely | Yes, always ] 

 (If you have suggestions for better wording in the English names of these options, please tell me!)

As we discussed in

https://github.com/mike-fabian/ibus-typing-booster/issues/158#issuecomment-1055100520

I am using the strategy to consider the best candidate as “extremely likely” only if these 4 conditions are met: 

  1.  the whole context can be found in a dictionary of a single language
  2. the whole context has a high user score because it has been typed many times before
  3. the suggestion doesn’t change the order of any letters
  4. the suggestion doesn’t change the length, only adds or removes accents *or* *changes* *only* *capitalization*

(I added this *or* *changes* *only* *capitalization*)

That means if inline completion is used with the recently added value “Yes, without fallback to popup”, this new autoselection option will in some rare cases show a popup: when an “extremely likely” candidate is available but cannot be shown inline because it would violate the rule that an inline completion should never change anything typed already. I am not sure whether this is the right thing to do, I could change it to never do that and observe the “Yes, without fallback to popup” even in this case. If I do that, the autoselection  would never do anything if inline completion  “Yes, without fallback to popup” is used, one would need to allow at least the fallback to the popup. 

But in this test release I allow a popup when autoselection happens even if the  inline completion mode “Yes, without fallback to popup”  is used.

I am also not so sure about my addition of allowing *changes* *only* *capitalization* when deciding whether a candidate is extremely likely or not. 

My intention was to fix “I like japan” Automatically to “I like Japan” because country names are always upper case in English.

But actually while I am testing this now I think I get far too many wrong capitalizations this way. 

So I will probably remove this capitalization hack again in 2.16.10. But tell me what you think about it!

**Comment by mike-fabian** [comment]
> Thanks, Mike: This is a very great improvement! It speeds up typing a lot!

I was less enthusiastic when testing, it saved a few key strokes here and there but it also inserted wrong stuff quite frequently which annoyed me a lot.


> Regarding auto-capitalization, maybe the dictionaries have the information about whether a word is the name of a country or of a person. If so, for these cases, the auto-capitalization feature could be kept.

No, the dictionaries don’t have that information.

I have removed this capitalization again already for 2.16.10, it was annoying me terribly, it was wrong for me more than 50% of the time.

**Comment by psads-git** [comment]
Well, I am quite enthusiastic regarding this new improvement! But if ibus-typing-booster is wrong too many times, maybe we could think on how to improve its precision. Or do you think this new feature is really unworthy, Mike?

**Comment by mike-fabian** [comment]
No, I’ll keep that feature, but without giving “very likely” candidates which change the capitalization, only those which change only accents seem to work resonably well for me.

Overall this new feature seems to be an improvement. But a very small improvement ...

**Comment by mike-fabian** [comment]
What do you think of the names of the new option?:

Automatically select the best candidate: [ No | Yes, but only when extremely likely | Yes, always ]

If these texts are OK, I would push these new translatable strings to git main already to give the translators time to translate it already at

https://translate.fedoraproject.org/projects/ibus-typing-booster/app/

before I make the official release with the new feature.

**Comment by psads-git** [comment]
I think the names are very fine, Mike!

**Comment by mike-fabian** [comment]
I pushed them, so they can be translated at https://translate.fedoraproject.org/projects/ibus-typing-booster/app/ now. 

I already did the German translations and Yuri Chornoivan already did the Ukrainian translation.

**Comment by psads-git** [comment]
I can do the translation to Portuguese, Mike.

**Comment by mike-fabian** [comment]
> I can do the translation to Portuguese, Mike.

Thank you very much! Your translations and the improvement for this issue here are included in:

https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.17.0

**Comment by mike-fabian** [comment]
Thank you very much for completing the translations 100% ❣️: 

![Screenshot](https://user-images.githubusercontent.com/2330175/178708414-cb64d80a-3e27-482d-80c1-10cf2b2c37b1.png)

**Comment by mike-fabian** [comment]
You can start the setup tool in Portuguese from the command line like that:

```
LC_ALL=pt_PT.UTF-8 python3 /usr/share/ibus-typing-booster/setup/main.py
```

**Comment by mike-fabian** [comment]
https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.17.1 contains your translations.

**Comment by psads-git** [comment]
Thanks, Mike. I have meanwhile checked my translation, which seems fine to me. Notwithstanding, if meanwhile I want to improve the translation of some specific words, how can I do that? Should I use the site:

https://translate.fedoraproject.org/projects/ibus-typing-booster/app/

?

**Comment by mike-fabian** [comment]
> Thanks, Mike. I have meanwhile checked my translation, which seems fine to me. Notwithstanding, if meanwhile I want to improve the translation of some specific words, how can I do that? Should I use the site:
> 
> https://translate.fedoraproject.org/projects/ibus-typing-booster/app/
> 
> ?

Yes.

**Comment by psads-git** [comment]
Thanks, Mike!
