### ISSUE TITLE
Latest news two years old?

### ISSUE THREAD

**Issue by guettli** [mike-fabian/ibus-typing-booster#29]
According to this page, the last news is from 2016: http://mike-fabian.github.io/ibus-typing-booster/news.html

I see two solutions:
* write more news
* remove the "news" section.

But maybe there are better solutions then these two.

**Comment by mike-fabian** [comment]
Yes, maybe I should remove the "news" section. There have been many improvements during these two years as you can see in the release notes: 

https://github.com/mike-fabian/ibus-typing-booster/releases

But duplicating these changes in "news" is not useful, or would that be useful?

**Comment by guettli** [comment]
I was told to avoid redundancy. A link to the release notes would be enough.

**Comment by mike-fabian** [comment]
Maybe I’ll write a new NEWS entry for the upcoming 2.0.0 release, there are really big changes which would make it useful to make it obvious that important things have changed.

**Comment by mike-fabian** [comment]
I added a NEWS entry for the 2.0.0 release now. Closing this issue.
