### ISSUE TITLE
Help installing tarball on Ubuntu 20.04. configure: error. No package 'ibus-1.0' found

### ISSUE THREAD

**Issue by 53R3n17Y-serenity** [mike-fabian/ibus-typing-booster#290]
Trying to install tarball Release 2.15.25 following instructions from here [ibus-typing-booster](https://mike-fabian.github.io/ibus-typing-booster/docs/dev/ "ibus-typing-booster")
Using Ubuntu store version is 2.9.6-1~ubuntu20.04.1 works fine.

After 
```bash
./configure --prefix=/usr --libexecdir=/usr/lib/ibus
```
I get this.
```bash
configure: error: Package requirements (ibus-1.0 >= 1.1.0) were not met:

No package 'ibus-1.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
```
```bash
sudo apt install ibus-1.0
```
```bash
E: Unable to locate package ibus-1.0
E: Couldn't find any package by glob 'ibus-1.0'
```
I do have `ibus/focal-updates,now 1.5.22-2ubuntu2.1 amd64` installed, among other ibus related packages.

I searched the web and this repo.
I have tried to play with adjusting the PKG_CONFIG_PATH (not sure if I was doing it right, following web examples, didn't help)
TIA

**Comment by mike-fabian** [comment]
I think you need to install `libibus-1.0-dev`:

```
sudo apt install libibus-1.0-dev
```

Does that solve your problem?

**Comment by 53R3n17Y-serenity** [comment]
@mike-fabian Thank you very much, got it working, rookie mistake.

Checked `libibus-1.0-dev`, not installed. Ok, checked the other required packages.
`libm17n-0, m17n-db, python3-packaging`, not installed.
I must have made a false presumption that since an APT version was working, I didn't need to check on requirements. Not a single time it crossed my mind to double-check everything from scratch. Unbelievable.
