### ISSUE TITLE
Cannot access preferences in Manjaro GNOME 42.1

### ISSUE THREAD

**Issue by AdithyaNair1234** [mike-fabian/ibus-typing-booster#299]
When clicking Preferences in the 3 dots in the Settings menu, Settings crashes and I have to Force Quit Settings. I am not able to enable Setup through the Top Bar in GNOME either.

**Comment by mike-fabian** [comment]
I guess you mean this:

![Screenshot](https://user-images.githubusercontent.com/2330175/168598620-d3fd2744-4f09-43b1-9d67-42afe970a8ac.png)

**Comment by mike-fabian** [comment]
This also happens on Fedora 36 and I reported it also in the Red Hat Bugzilla:

https://bugzilla.redhat.com/show_bug.cgi?id=2073306

It happens only when using Gnome on Wayland, it works when using Gnome on Xorg.

**Comment by mike-fabian** [comment]
> When clicking Preferences in the 3 dots in the Settings menu, Settings crashes and I have to Force Quit

This happens not only for ibus-typing-booster but for *all* ibus input methods (You can try the Japanese input method ibus-anthy for example or the Chinese input methods “Intelligent Pinyin”, it happens for all.

So I am pretty sure that this has nothing to do with ibus-typing-booster but is a problem in Gnome.

> I am not able to enable Setup through the Top Bar in GNOME either.

This works for me though.

What also works is opening the setup from the command line like this:

```
python3 /usr/share/ibus-typing-booster/setup/main.py
```

As opening the ibus-typing-booster setup from the command line works, it doesn’t seem likely that not being able to open it from the gnome-control-center has anything to do with ibus-typing-booster.

**Comment by mike-fabian** [comment]
Carlos Garnacho fixed this issue in:

https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4789
