### ISSUE TITLE
[request] Add Ubuntu 16.X tutorial for installation in README

### ISSUE THREAD

**Issue by arpan-chavda** [mike-fabian/ibus-typing-booster#3]
If you have time, generate debs for it.
Thanks.

**Comment by mike-fabian** [comment]
There is a package available here: https://launchpad.net/~alexepico/+archive/ubuntu/ppa/+packages

Although that is not the latest version of ibus-typing-booster.

**Comment by arpan-chavda** [comment]
Thanks. I will try and report here.

**Comment by mike-fabian** [comment]
Did the package work for you?

**Comment by mike-fabian** [comment]
I added  some  information about how to install on Ubuntu here:

http://mike-fabian.github.io/ibus-typing-booster/development.html

Maybe you can try whether this works for you and whether there is anything wrong
or incomplete in what I wrote about Ubuntu there.

It worked for me. Here is a screenshot on ubuntu-16.04:

![ibus-typing-booster-on-ubuntu-16 04](https://cloud.githubusercontent.com/assets/2330175/22053804/4a288db4-dd53-11e6-8746-1acaf8e3ccab.png)

**Comment by mike-fabian** [comment]
I am closing this issue because I added information about how to install it on Ubuntu 16.04.
