### ISSUE TITLE
Spaces not added when continuing writing words in Wayland

### ISSUE THREAD

**Issue by rugk** [mike-fabian/ibus-typing-booster#31]
STR:
* Open gedit.
* Write something with spaces and do not use suggestions (i.e. just go on writing)

## What happens?
![spaces](https://user-images.githubusercontent.com/11966684/40315990-3101249a-5d1d-11e8-80dc-dec0a1a23fc4.gif)

I actually have to press space two times to add a space. The first press seems to hide the popup, the second then actually add the space.

## What should happen?

Actually a funny thing is that it works correctly in Firefox. There I can write spaces or don't write them, whatever.

Fedora 28, GNOME
Firefox 60
typing booster 1.5.37

**Comment by rugk** [comment]
Oky, I guess I know the reason wyh Firefox works: When I press Down+Enter there to select the first suggestion, it also actually adds a new line in Firefox. So it seems Firefox catches the input before typing-booster can.

**Comment by rugk** [comment]
Ah, so this is a dupe of https://github.com/mike-fabian/ibus-typing-booster/issues/12. As you see I am still experiencing this error.

**Comment by rugk** [comment]
I just found the option, sorry. Now it works…

So it mentions "X Input Method"  but I think I should be fine using it as I use Wayland, so well… (and Firefox runs under XWayland and still seems to work…)

**Comment by mike-fabian** [comment]
That option is actually intended for Qt5 programs, not for gedit. 

I just tested that you are right and that a similar problem occurs in Fedora 28 when gedit is used in a Gnome-Wayland session. It works correctly in a Gnome-Xorg session.

So that workaround for Qt happens to help in that case as well, but that is strange. I think it should work in a Gnome-Wayland session without that workaround. But I  just verified that it  does not work in a Gnome-Wayland session. Not only in gedit, but apparently in *all* Gnome programs.

**Comment by rugk** [comment]
Okay…

**Comment by bepolymathe** [comment]
Where are we with this problem?

**Comment by bepolymathe** [comment]
I have the impression that this comes from the fact that I cannot save the "auto-validation" parameters...

**Comment by bepolymathe** [comment]
It don't works too under X11 with gedit for me... 😿

**Comment by mike-fabian** [comment]
For me it works fine under X11 with gedit.

**Comment by mike-fabian** [comment]
What are the “auto-validation” parameters?

**Comment by bepolymathe** [comment]
> What are the “auto-validation” parameters?

This is for characters that can be inserted in a dialog box in the parameters (validation for pre-edition). This is the French translation...

**Comment by bepolymathe** [comment]
Is this box empty for you when you try on X11 ?

**Comment by mike-fabian** [comment]
![ibus-typing-booster-setup](https://user-images.githubusercontent.com/2330175/42823728-8e98eee2-89de-11e8-87f2-4544c3ba98a7.png)

You mean the option "Auto commit characters:” in my screenshot?

This entry is empty by default.

If you add 
```
«.;,:!?)»
```
there, these characters will trigger an automatic commit.
I just tried again and this works for me. Personally I leave this field empty because
I don’t want any characters to commit automatically, but that is a matter of taste.

**Comment by bepolymathe** [comment]
Yes, absolutely!
I wanted to try this option but I realized that the settings don't want to register... and I don't understand why.

**Comment by bepolymathe** [comment]
My windows look like this : 

![image](https://user-images.githubusercontent.com/29939805/42824625-794c5c66-89e0-11e8-89af-56b58b525849.png)

**Comment by bepolymathe** [comment]
But the most annoying problem is this obligation to type twice space to have a space in all applications except Firefox. I just tried with libreoffice and it's the same.

**Comment by bepolymathe** [comment]
And I just tried again... I confirm that I have the same behavior with X org...

**Comment by mike-fabian** [comment]
It does not happen for me because I don’t use wayland at the moment. This  problem occured in  wayland in Fedora 28.

**Comment by mike-fabian** [comment]
All applications I tried including libreoffice and gedit work for me under X11.

**Comment by mike-fabian** [comment]
What distribution are you using?

**Comment by bepolymathe** [comment]
Well, Fedora 28... Gnome Version 3.28.2
Mainly under Wayland.

**Comment by bepolymathe** [comment]
So if I enable bugfixing for Qt in the X org session... it seems to work. 

![image](https://user-images.githubusercontent.com/29939805/42825929-727aa9f8-89e3-11e8-81b1-834eaa0c1977.png)

**Comment by bepolymathe** [comment]
And then back on Wayland... it also works on Wayland ! :face_with_head_bandage: 
Strange behavior ?

**Comment by mike-fabian** [comment]
Yes, that workaround makes it also work on Wayland.
*But* that workaround causes a lot of problems when trying to use ibus-typing-booster to
type into X11 programs like xterm.

Wayland on Fedora 28 has some bug at the moment which can  be worked around by using that  option
which is actually intended for Qt4 and Qt5. Wayland on Fedora 27 worked just fine.  

But Gnome under Xorg works fine for me without that workaround on Fedora 28 as well. I just 
tried again Gnome under Xorg on Fedora 28 and had no problems using ibus-typing-booster.

**Comment by bepolymathe** [comment]
Okay. All right. 

But then, for me i need the workaround whether it's on Wayland or Xorg if I want ibus-typing-booster to be usable. So I'll keep testing it under Wayland with the active bug workaround, and I'll tell you what it looks like. 
Thanks for your responsiveness.

**Comment by mike-fabian** [comment]
It is a mystery to me why it doesn’t work for you on Fedora 28 Gnome Xorg without the workaround.
But at least it is good that this workaround helps you. The only disadvantages I know of
using that workaround is that ibus-typing-booster is unusable then for typing into X11 programs like
xterm.

**Comment by bepolymathe** [comment]
Yes... I've seen what it looks like. That's funny ;-)
But that's all right, in the terminal I'm going back to ["bepo"](https://en.wikipedia.org/wiki/Keyboard_layout#B%C3%89PO)!

**Comment by mike-fabian** [comment]
Spaces are added now after a commit in Gnome Wayland on Fedora 34 **without** using the workaround option

   [✔️] Use a workaround for a bug in Qt im module

Looks like the problem in Wayland has been fixed.

Closing this issue.
