### ISSUE TITLE
[BUG] typing on Chromium still not working on wayland 

### ISSUE THREAD

**Issue by elhananjair** [mike-fabian/ibus-typing-booster#315]
**Describe the bug**

**To Reproduce**
1. open chromium 
2. change the keyboard to Amharic

**Expected behavior**
Write in amharic language 

**Screenshots or videos**

**ibus-typing-booster version?**
Open the ibus-typing-booster setup tool and click on the `About` button (Or check the version of the installed package, for example using `rpm -q ibus-typing-booster` on rpm based distribtions).
1.5.26
**ibus version?**
ibus-1.5.26-8.fc36.x86_64

**Distribution and version?**
For example Fedora 35, Ubuntu 20.04, FreeBSD 11.1, …

**Desktop and version?**
For example Gnome 3, KDE, XFCE, i3, ...

**Xorg or Wayland?**
Wayland 

**Additional context**
Hello @mike-fabian I have asked this question before, I am using Firefox for now because it works fine on that but I have on chromium no luck. It writes in English even though I change the keyboard.

**Comment by mike-fabian** [comment]
That problem does not only affect Amharic and not only ibus-typing-booster, **all** ibus input method do not work in chromium in Wayland.

**Comment by mike-fabian** [comment]
A an alternative to chromium, you have not only firefox available, you could also use google-chrome. ibus input in google-chrome in Wayland works.

**Comment by mike-fabian** [comment]
A workaround for chromium on Wayland:

If you start chromium like this:

```
GTK_IM_MODULE=ibus chromium-browser --gtk-version=4
```

Then ibus input in chromium in Wayland works! 

If you do that, I strongly recommend to also update ibus-typing-booster to the latest 2.16.1 version because that has an important fix when using the Gtk4 input module!

**Comment by mike-fabian** [comment]
Oh, and for the fix for the Gtk4 input module you also need ibus >= 1.5.27 which is not yet released ☹.
On Fedora 36, you could use the latest ibus build from https://copr.fedorainfracloud.org/coprs/fujiwara/ibus/builds/ to get the fix for Gtk4.

Without the fix for Gtk4, input will basically work but some problems in the details remain like having to press ENTER or RETURN twice to get a new line.

**Comment by elhananjair** [comment]
Ok, thanks @mike-fabian

**Comment by elhananjair** [comment]
@mike-fabian hello there I have always have been using Firefox for a while and just tried chromium with `GTK_IM_MODULE=ibus chromium-browser --gtk-version=4` it doesn't still work. 

And non-related to this issue I don't how non-English languages are not working on the KDE Konsole terminal.

**Comment by mike-fabian** [comment]
For KDE on Xorg you might need to have QT_IM_MODULE=ibus in your environment.

**Comment by mike-fabian** [comment]
If you use KDE wayland on Fedora 37 with all updates, ibus should work, try to use 'im-chooser' to select ibus.

**Comment by elhananjair** [comment]
Yeah am already using ibus, but still not working and am on Fedora 37 with all thing updated 
![Screenshot_20230305_173728](https://user-images.githubusercontent.com/69236638/222967075-43fd4554-dbab-46b7-8599-7391839d1615.png)

**Comment by mike-fabian** [comment]
And do you have QT_IM_MODULE=ibus set in the environment?

If you type `env | grep ibus` in konsole, what do you get?

**Comment by elhananjair** [comment]
> And do you have QT_IM_MODULE=ibus set in the environment?
yes

![Screenshot_20230305_213415](https://user-images.githubusercontent.com/69236638/222979118-68844b9f-360f-4ec3-a745-9228a143d087.png)

**Comment by mike-fabian** [comment]
The environment variables look good. Your screenshot shows that it works in
kate, but not in konsole?

What happens if you start another konsole from the first one? If that
works, that would mean that these environment variables were not yet set
when the first konsole started. This happened to me a few times when
testing ibus on KDE.

In that case it should help to set these environment variables in `~/.
profile` to set them early enough.

**Comment by elhananjair** [comment]
> The environment variables look good. Your screenshot shows that it works in
kate, but not in Konsole?

Yes you're totally right. I tried to open it and it worked, Chromium is still not working though. 

![Screenshot_20230305_221520](https://user-images.githubusercontent.com/69236638/222981005-d4edae22-bdbb-4683-8704-46761f73c379.png)

> In that case it should help to set these environment variables in `~/.
profile` to set them early enough.

ok I will add it there, have you noticed the password shows up as I typed in Konsole? just wanted to mention it

**Comment by elhananjair** [comment]
![Screenshot_20230305_222637](https://user-images.githubusercontent.com/69236638/222981446-c41cc0b8-f535-448a-a058-cebc61deb6d1.png)

I just noticed that I haven't added QT_IM_MODULE=ibus yet, I just added and re-opened and no luck

**Comment by mike-fabian** [comment]
Even restarting the KDE session doesn't do it? Then I don't know at the moment, it worked for me not long ago when I tested KDE on Fedora 37.

**Comment by mike-fabian** [comment]
If KDE Wayland doesn't work for you, you can also try KDE Wayland. Both did work for me with ibus when I tried recently. But there are usually more bugs on Wayland when ibus is used. And some features don't work on Wayland, for example the preedit on Wayland is always black and white, no colours in the preedit are possible on wayland. That makes some features of Typing Booster like inline completion very difficult to use on Wayland.

**Comment by elhananjair** [comment]
> Even restarting the KDE session doesn't do it?

After I set that variable to ~/.profile I restarted my computer and it didn't work. 

> If KDE Wayland doesn't work for you, you can also try KDE Wayland
you meant X11 right? 


Yeah, I don't why on every update there might be some slight change on Wayland which might break something. You are doing a good job though, thank you so much. I am ditching firefox that's why I started using chromium often, I have mentioned some issues regarding ibus-typing-booster on the Nextcloud office application and the problem only can be reproducible on Firefox while it works fine on chrome*.

**Comment by mike-fabian** [comment]
I tried to create a nextcloud test account to reproduce that issue but I could not create an account, the confirmation email never arrived. I will try that again when I am back from vacation.

**Comment by mike-fabian** [comment]
Oh, I wrote KDE Wayland twice in my previous to last comment, I wanted to say it might help to try KDE Xorg.

**Comment by elhananjair** [comment]
> Oh, I wrote KDE Wayland twice in my previous to last comment, I wanted to say it might help to try KDE Xorg.

Yeah, I knew that I am just afraid of using Xord since it is not getting that much attention from the developers and every eye is on Wayland, let me wait a little bit more and I will consider using google-chrome instead.
