### ISSUE TITLE
Menu appears at wrong position on the screen in Firefox

### ISSUE THREAD

**Issue by rugk** [mike-fabian/ibus-typing-booster#33]
The popup sometimes does not appear at the position I am currently writing at, but at the one I _just wrote_ at. (i.e. the previous position):

![wrongpos](https://user-images.githubusercontent.com/11966684/40316755-9e259ebe-5d1f-11e8-94bf-06161d5616eb.png)

Fedora 28, GNOME
Firefox 60
typing booster 1.5.37

**Comment by mike-fabian** [comment]
This is a generic problem with ibus and/or Wayland or Xorg.

ibus-typing-booster cannot control where this pops up. 

So either it is a bug in ibus or in wayland and should be reported there.
