### ISSUE TITLE
Option to exclude applications

### ISSUE THREAD

**Issue by rugk** [mike-fabian/ibus-typing-booster#34]
I e.g. do not really like that  is also active in the terminal.

It could also help to workaround https://github.com/mike-fabian/ibus-typing-booster/issues/26, as we may just exclude terminals. The typing booster may not be useful there, anyway.

**Comment by mike-fabian** [comment]
I think  there is  no way to exclude terminals  from ibus-typing-booster, ibus-typing-booster has no way to figure out whether the program typed into is a terminal or something else.

On top of that, some people run IRC clients or mail programs in terminals where the completion of ibus-typing-booster is very useful. So even if excluding terminals were possible, it would not be a good idea to do that by default.

**Comment by rugk** [comment]
No of course not by default, but letting the user to define a list of applications.

**Comment by mike-fabian** [comment]
But how? I don’t think this is possible.

And it is certainly not an ibus-typing-booster problem but an ibus problem then. Because this problem is the same for *all* ibus input methods.

**Comment by rugk** [comment]
So yeah… if it is not possible, it is not possible.
