### ISSUE TITLE
apt-Package unavailable? 

### ISSUE THREAD

**Issue by anreji** [mike-fabian/ibus-typing-booster#348]
[The docs](https://mike-fabian.github.io/ibus-typing-booster/docs/user/#0) suggest, that there should be packages available for Ubuntu (-based) distros, but I can't install under Pop!OS, neither via `apt install ibus-typing-booster`, nor via searching for "typing-booster" in the GUI app store (which [this video](https://mike-fabian.github.io/ibus-typing-booster/videos/user-docs/installing-using-ubuntu-software-on-ubuntu-21.04.webm) suggests worked at some point as well).
So either I'm doing something wrong (and if I do, help would be appreciated :P), or the documentation should be changed to reflect that the packages aren't available anymore.

**Comment by mike-fabian** [comment]
Isn’t the right command 
```
apt-get install ibus-typing-booster
```

?

**Comment by mike-fabian** [comment]
Maybe you need to add ubuntu repositories as described here: https://apt.pop-os.org/

**Comment by anreji** [comment]
Has to be an error on my part, because installing on my Kubuntu laptop works like a charm.
FYI `apt install` essentially does the same as `apt-get install` (but there are [articles](https://itsfoss.com/apt-vs-apt-get-difference/) that describe the difference in detail) and _I think_ the repos you've linked to should come preinstalled with the OS (that's what the first sentence on the page says, anyway).
All in all it seems to be some Pop!OS-specific quirk or I'm missing something, either way it's not your problem, so I think we can close :)
