### ISSUE TITLE
[ENHANCEMENT] It should be possible to set options for m17n input methods in the typing booster setup tool

### ISSUE THREAD

**Issue by mike-fabian** [mike-fabian/ibus-typing-booster#360]
See https://github.com/mike-fabian/m17n-db-bn-national-jatiya/issues/1
especially this comment: https://github.com/mike-fabian/m17n-db-bn-national-jatiya/issues/1#issuecomment-1220531749

**Comment by mike-fabian** [comment]
https://user-images.githubusercontent.com/2330175/188243119-307848ae-4963-4821-becc-91d522575a98.mp4

**Comment by mike-fabian** [comment]
The video shows that setting the variable for bn-national-jatiya works
with the test builds from 
https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/

Changing the variable has an immediate effect, no `ibus restart` is necessary.

**Comment by mike-fabian** [comment]
Video showing the new feature for a few othe input methods like mr-gamabhana and ja-anthy:

https://user-images.githubusercontent.com/2330175/188263926-525bdf59-4743-4ff8-916b-8ebd6deab226.mp4

**Comment by Mahmudul-hasan613** [comment]
> I have just pushed a release-candidate-2.18.12 branch:
> https://github.com/mike-fabian/ibus-typing-booster/tree/release-candidate-2.18.12
> If you want to try a build and install from source you can checkout that branch.
> Instructions on how to build are here:
> https://mike-fabian.github.io/ibus-typing-booster/docs/dev/

Do I need to uninstall the previous version of ibus-typing-booster on my computer before downloading and installing the source files from github...?

**Comment by Mahmudul-hasan613** [comment]
> ibus-typing-booster-release-candidate-2.18.12

In what sense is the word candidate used in...? If I understand this, then it will be easy for me to translate the user interface to Bengali.

**Comment by mike-fabian** [comment]
> computer

No, you can overwrite the existing installation.

**Comment by mike-fabian** [comment]
> > ibus-typing-booster-release-candidate-2.18.12
> 
> In what sense is the word candidate used in...? If I understand this, then it will be easy for me to translate the user interface to Bengali.

https://mike-fabian.github.io/ibus-typing-booster/docs/user/#4_1

If you look at the video at this URL of the documentation, you see that while typing a box containing suggested words pops up. These are the "candidates" and this popup is the "candidate list"

**Comment by Mahmudul-hasan613** [comment]
I think ibus-typing-booster doesn't have any dictionary for Bengali language.

**Comment by mike-fabian** [comment]
> I think ibus-typing-booster doesn't have any dictionary for Bengali language.

https://packages.debian.org/sid/hunspell-bn

You need to install the Bengali dictionary package.

On Debian, Ubuntu, and Fedora it is called hunspell-bn

**Comment by mike-fabian** [comment]
Then you need to add the bn_BD dictionary in the ibus-typing-booster setup tool.

Even if you don't have a Bengali dictionary, ibus-typing-booster will remember the words you typed and show them as candidates when you type the same words again.

**Comment by Mahmudul-hasan613** [comment]
> https://packages.debian.org/sid/hunspell-bn
> 
> You need to install the Bengali dictionary package.
> 
> On Debian, Ubuntu, and Fedora it is called hunspell-bn

It worked.

**Comment by Mahmudul-hasan613** [comment]
> Even if you don't have a Bengali dictionary, ibus-typing-booster will remember the words you typed and show them as candidates when you type the same words again.

It is a very good option. This way I don't have to type the same word over and over again.

**Comment by Mahmudul-hasan613** [comment]
I am using the new test version. It is working very well. In particular, I am using my own translation. It gives me a different feeling.

**Comment by mike-fabian** [comment]
No need to hurry, it is great that you are doing the translation!

**Comment by mike-fabian** [comment]
> I am using the new test version. It is working very well. In particular, I am using my own translation. It gives me a different feeling.

Does changing the option “use-automatic-vowel-forming” work for you?

Of course I tested it and it seems to work well for me, but I had to write a lot of code to add this feature and I may have made mistakes somewhere. It would be great if you can confirm that it works for you as well.

**Comment by Mahmudul-hasan613** [comment]
> Of course I tested it and it seems to work well for me, but I had to write a lot of code to add this feature and I may have made mistakes somewhere. It would be great if you can confirm that it works for you as well.

I didn't find any problem using ibus-typing-booster. If I find any problem, I will report that problem to you.

**Comment by Mahmudul-hasan613** [comment]
> If you look at the video at this URL of the documentation, you see that while typing a box containing suggested words pops up. These are the "candidates" and this popup is the "candidate list"

Oh well, so the word suggestion facility is called "candidates"...?

**Comment by mike-fabian** [comment]
> > If you look at the video at this URL of the documentation, you see that while typing a box containing suggested words pops up. These are the "candidates" and this popup is the "candidate list"
> 
> Oh well, so the word suggestion facility is called "candidates"...?

Yes.

**Comment by mike-fabian** [comment]
> [Ibus issues 2420](https://github.com/ibus/ibus/issues/2420#issuecomment-1180364228) you have discussed preedit and commit very nicely. As far as I can understand from that discussion, preedit means "unfinished edit" ie the writing is not finished yet or "pre edit". And commit means when I press the space key to finish writing a word.
> If I understand correctly, then I will proceed with the translation of ibus-typing-booster.

Yes, you are describing preedit and commit correctly.

**Comment by mike-fabian** [comment]
This is included in the ibus-typing-booster-2.19.0 release: https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.19.0
