### ISSUE TITLE
relies outdated ibus-m17n

### ISSUE THREAD

**Issue by baimafeima** [mike-fabian/ibus-typing-booster#4]
I'd like to have ibus-typing-booster included in the Solus repositories. As it currently relies on ibus-m17n it cannot be included. Is there any way to address this issue? Feel free to get involved here:
https://dev.solus-project.com/T951

Testing system: Solus (https://www.solus-project.com/)

**Comment by mike-fabian** [comment]
It requires m17n-lib and m17n-db but *not* ibus-m17n.

**Comment by baimafeima** [comment]
Thank you for your feedback and getting in touch on the dev tracker.
