### ISSUE TITLE
[BUG] Ibus booster not working on Fedora 37 KDE 

### ISSUE THREAD

**Issue by elhananjair** [mike-fabian/ibus-typing-booster#412]
**Describe the bug**
ibus-booster is by default installed on my fedora 37 KDE, and I tried to add ibus-booster in the input-method setting and added my language, Amharic. I set shortcuts for changing input methods with CTRL+SPACE, I tried almost in many apps and when I changed the input method to Amharic it still shows English letters. 

**To Reproduce**
1. Go to ibus-booster setup
2. Add Amharic as input method in ibus-booster
3. try to switch to amharic and write on some app
4. It will not show the amharic letters 

**Expected behavior**
should have switch the input method to amharic

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/69236638/214538706-857167a4-99af-4a10-adc6-977095594dd6.png)

**ibus-typing-booster version?**
Open the ibus-typing-booster setup tool and click on the `About` button (Or check the version of the installed package, for example using `rpm -q ibus-typing-booster` on rpm based distribtions).

**ibus version?**
Run `ibus version` (Or check the version of the installed package, for example using `rpm -q ibus` on rpm based distribtions).
2.19.13
**Distribution and version?**
For example Fedora 35, Ubuntu 20.04, FreeBSD 11.1, …
Fedora 37 KDE 
**Desktop and version?**
KDE 5.26.5

**Xorg or Wayland?**
You can check this with `echo $XDG_SESSION_TYPE`
Wayland
**Additional context**

**Comment by mike-fabian** [comment]
My guess is that `QT_IM_MODULE=ibus` is not set.

I just tried with a rawhide virtual machine (You have Fedora 37 but Fedora rawhide is probably no big difference)

When I logged into Plasma(Wayland) and opened a konsole, `QT_IM_MODULE=ibus` was not set in that konsole and I could not input Amharic into that konsole.

But `ps aux | grep ibus` showed that ibus was running and I was able to select typing booster in the panel.

Then I started a  second konsole from the first one using:

```
QT_IM_MODULE=ibus konsole
```

and in that second konsole I could input Amharic.

See this screenshot:

![Screenshot](https://user-images.githubusercontent.com/2330175/214572398-dde80633-2c88-4697-ab90-effd64729abc.png)

**Comment by mike-fabian** [comment]
You also see in my screenshot that I have the am-sera input method with higher priority in the setup tool of ibus-typing-booster.

While typing one can see only the result of the highest priority input method in the preedit although all configured input methods are tried to find candidates for the popup.

You don't have to open the setup tool to switch the order of the input methods, there are key bindings to switch the the next and the previous input method which are `Control+Up` and `Control+Down` by default.

**Comment by mike-fabian** [comment]
Now I logged out of Plasma(Wayland) and logged in to Plasma(X11) without changing anything else and I found that the ibus-specific environment variables were set and I could type Amharic out of the box with ibus-typing-booster.
See this screenshot:

![Screenshot](https://user-images.githubusercontent.com/2330175/214573807-ef5553cf-80fa-4398-b144-0f8b60e45e40.png)

**Comment by elhananjair** [comment]
> 

Yeah, I have set key bind for the next input method, I just used the setup tool for showing the issue. I will give Amharic the highest priority as you suggested.

**Comment by elhananjair** [comment]
> Now I logged out of Plasma(Wayland) and logged in to Plasma(X11) without changing anything else and I found that the ibus-specific environment variables were set and I could type Amharic out of the box with ibus-typing-booster. See this screenshot:
> 
> ![Screenshot](https://user-images.githubusercontent.com/2330175/214573807-ef5553cf-80fa-4398-b144-0f8b60e45e40.png)

Therefore this issue is only occurring in Wayland, right? Oh many things are broken in Wayland 😢😢

**Comment by mike-fabian** [comment]
This bug seems to be related: https://bugzilla.redhat.com/show_bug.cgi?id=2157582

**Comment by mike-fabian** [comment]
Apparently, if you install this update:
https://bodhi.fedoraproject.org/updates/FEDORA-2023-b666bfa158
And also  install the imsettings-plasma provided by this update, it will work.

**Comment by elhananjair** [comment]
Thank you so much it worked now after I installed those 🙏🏽

**Comment by mike-fabian** [comment]
> Thank you so much it worked now after I installed those 🙏🏽

Great, I have also just tested this and it made it work for me on Plasma(Wayland) as well.

So I am closing this issue here.
