### ISSUE TITLE
Unable to open settings in Manjaro.

### ISSUE THREAD

**Issue by SalchiPapa** [mike-fabian/ibus-typing-booster#42]
Clicking the settings menu doesn't bring the settings menu. How could I debug this?

**Comment by mike-fabian** [comment]
Is there anything in the log file? The log file for the setup tool is here:
~/.local/share/ibus-typing-booster/setup-debug.log

**Comment by mike-fabian** [comment]
You mean the settings menu for  ibus-typing-booster which is shown in the Gnome-panel?

You can also start the setup tool manually like this:

python3 /usr/share/ibus-typing-booster/setup/main.py

Does starting it manually make any difference?

Also, while using ibus-typing-booster, AltGr+F10 should also start the setup tool.

**Comment by mike-fabian** [comment]
Could you find  anything?

**Comment by SalchiPapa** [comment]
Hi!

I tried also with Debian, same result. Calling directly:

`python3 /usr/share/ibus-typing-booster/setup/main.py` works!

I have altgr configured as compose key.

After opening the settings via command line, and tweaking stuff, I can see output in the log, but if I click the icon in the taskbar nothing happens no output in the log at all, I can make a video if it is useful.

It's as if literally the settings icon wasn't bound to any action.

**Comment by mike-fabian** [comment]
I  am not exactly sure about what taskbar you are talking, is this the setup entry  in the gnome panel? 

![ibus-typing-booster-setup-menu-gnome-panel](https://user-images.githubusercontent.com/2330175/50330610-2de89e00-04fc-11e9-925d-90ddaf47632a.png)

**Comment by SalchiPapa** [comment]
I am using KDE in Manjaro and Cinnamon in Debian, I'll put some pictures ready later in the day.

**Comment by SalchiPapa** [comment]
This is the option in theManjaro's KDE KIM Panel, it doesn't do anything, no log report either.
This is the option in theManjaro's KDE KIM Panel, it doesn't do anything, no log report either.

![image](https://user-images.githubusercontent.com/4594825/50348561-b7996b00-04fe-11e9-8c6c-47c10b4bdac2.png)

This is in KDE Manjaro, using the default widget (it doesn't interate to the KDE pannel, the result is the same. No menu pops up, no log activity.
 
![image](https://user-images.githubusercontent.com/4594825/50348667-1363f400-04ff-11e9-9d3d-b8b5f8f5fc12.png)

Menu works if it's invoked form the command line.

In Cinnamon, the ibus widget integrates to the cinnamon pannel, but it is the same, no log output when trying to launch setup and also no menu pops up. However it works when invoked from the command line.

I'll upload an image from Cinnamon later today.

Thank you very much for your help.

**Comment by mike-fabian** [comment]
Do these two files exist on your system?:

/usr/libexec/ibus-engine-typing-booster
/usr/libexec/ibus-setup-typing-booster

?

If yes, what do they contain?

**Comment by mike-fabian** [comment]
Do these two files exist on your system?:

/usr/libexec/ibus-engine-typing-booster
/usr/libexec/ibus-setup-typing-booster

?

If yes, what do they contain?

**Comment by SalchiPapa** [comment]
Thanks for your reply.

I can check in Manjaro right now and this files don't exist in that machine. I'll test in Debian as soon as possible.

Best regards.

**Comment by SalchiPapa** [comment]
In Manjaro I installed it from the official repositories.

In Debian, I followed the ArchLinux instructions for their official package:

* https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/ibus-typing-booster

```
cd ibus-typing-booster
autoreconf -fvi
./configure --prefix=/usr --libexec=/usr/lib/ibus
sudo make install
cd /usr/share/ibus-typing-booster/data
gzip -nf --best *.{txt,json} annotations{,Derived}/*.xml
```

**Comment by mike-fabian** [comment]
Ah, OK, I see. So you probably have 

/usr/lib/ibus/ibus-engine-typing-booster
/usr/lib/ibus/ibus-setup-typing-booster

And /usr/lib/ibus/ibus-engine-typing-booster contains the line:

export IBUS_TYPING_BOOSTER_LIB_LOCATION=${prefix}/libexec

which is wrong. If you fix that line to look like 

export IBUS_TYPING_BOOSTER_LIB_LOCATION=${prefix}/lib/ibus

then the setup tool will probably start when you click the button in the panel.

My mistake, I’ll fix this for the next  release.

**Comment by mike-fabian** [comment]
This patch should fix the problem:
```
diff --git a/engine/ibus-engine-typing-booster.in b/engine/ibus-engine-typing-booster.in
index 6a70470..0ca19de 100755
--- a/engine/ibus-engine-typing-booster.in
+++ b/engine/ibus-engine-typing-booster.in
@@ -19,8 +19,10 @@
 
 PYTHON=@PYTHON@
 prefix=@prefix@
+exec_prefix=@exec_prefix@
+libexecdir=@libexecdir@
 export IBUS_TYPING_BOOSTER_LOCATION=${prefix}/share/ibus-typing-booster
-export IBUS_TYPING_BOOSTER_LIB_LOCATION=${prefix}/libexec
+export IBUS_TYPING_BOOSTER_LIB_LOCATION=${libexecdir}
 export PYTHONIOENCODING=UTF-8
 
 # Set this variable to something > 0 to get more debug output.
-- 
```

**Comment by mike-fabian** [comment]
Fixed in https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.4.1
