### ISSUE TITLE
[BUG] ibus-typing-booster causing a problem on Nextcloud Office

### ISSUE THREAD

**Issue by elhananjair** [mike-fabian/ibus-typing-booster#424]
**Describe the bug**
When I type on Nextcloud Office/Collabora Online app, the first letter reedited with the letter I type, and until recent times I thought the problem was with collabora online, but when I changed input method from Ibus-typing-booster to the default one, it worked fine. 

**To Reproduce**
1. Go to firefox 
2. Create a new document and start to type something as nextcloud office opens the document 
3. The first letter you type won't appear 

**Expected behavior**
As in other browsers, it should appear as you type any letter. 

**Screenshots or videos**
It skips the first letter I enter and shows the second or third letter I type. 

**ibus-typing-booster version?**
2.21.3-1

**ibus version?**
1.5.27-5

**Distribution and version?**
Fedora 37

**Desktop and version?**
KDE

**Xorg or Wayland?**
Wayland

**Additional context**
[I have opened an issue on Collabora online](https://github.com/CollaboraOnline/online/issues/5867)

**Comment by elhananjair** [comment]
@mike-fabian I think the this issue might be related to the one you fixed [here](https://github.com/mike-fabian/ibus-typing-booster/issues/471)

**Comment by mike-fabian** [comment]
Does this fix solve the problem here as well?

**Comment by mike-fabian** [comment]
I could not reproduce the problem in nextcloud office because creating a nextcloud account didn't work for me when I tried. I must try again.

**Comment by mike-fabian** [comment]
@elhananjair Is the problem fixed in the latest version of ibus-typing-booster?

**Comment by mike-fabian** [comment]
I have released https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.24.10 which might fix this issue here as well. Can you test this please?

**Comment by elhananjair** [comment]
I will check and let you know, will it be released as a package too? since I have installed ibus-typing-booster through dnf

**Comment by mike-fabian** [comment]
> I will check and let you know, will it be released as a package too? since I have installed ibus-typing-booster through dnf

Packages for Fedora 38, 39, and rawhide are here:
https://bodhi.fedoraproject.org/updates/?search=ibus-typing-booster

In your original report you write that you were using Fedora 37. But I guess you have updated to Fedora 38 or Fedora 39 in the meantime. If you are on Fedora 38 or Fedora 39 you can easily install the update with dnf with the instructions given here:

Fedora 39: https://bodhi.fedoraproject.org/updates/FEDORA-2023-0450d1b7e5

Fedora 38: https://bodhi.fedoraproject.org/updates/FEDORA-2023-42e4b64dca

Currently the update is  still in "testing". As soon as it goes to "stable" (maybe in two weeks), a normal "dnf update" will install the package for you.

**Comment by mike-fabian** [comment]
The Fedora 38 and Fedora 39 packages are in "stable" now, i.e. `sudo dnf update ibus-typing-booster` should give you ibus-typing-booster-2.24.10 now.

**Comment by elhananjair** [comment]
Ok I will check it sorry for the delay, I wasn't able to access Nextcloud recently, I will confirm it tomorrow

**Comment by mike-fabian** [comment]
Were you able to check the problem in Nextcloud?

**Comment by elhananjair** [comment]
@mike-fabian I am very sorry for the delay, I was busy and couldn't test it. 
Yes, it's working now, the problem is solved now.

**Comment by mike-fabian** [comment]
> @mike-fabian I am very sorry for the delay, I was busy and couldn't test it. Yes, it's working now, the problem is solved now.

Thank you very much!
