### ISSUE TITLE
Is there a Slackware package for ibus-typing-booster?

### ISSUE THREAD

**Issue by Geremia** [mike-fabian/ibus-typing-booster#436]
Is there a Slackware package or [SlackBuild](https://www.slackwiki.com/Writing_A_SlackBuild_Script) for ibus-typing-booster?

**Comment by mike-fabian** [comment]
I am not aware of a build Slackware.

I would be happy if somebody creates one and maintains it.

**Comment by mike-fabian** [comment]
I cannot really do anything about this, I have no time to maintain a slackware package.
I think it is better to report this to slackware or maybe you could maintain it for slackware?

Even if there is no package, it is not very difficult to build ibus-typing-booster from source.
See the documentation at:

https://mike-fabian.github.io/ibus-typing-booster/docs/dev/

If you have problems building from source and need help, you can ask me.

**Comment by Geremia** [comment]
@mike-fabian cf. [this LinuxQuestions.org thread](https://www.linuxquestions.org/questions/showthread.php?p=6422876). 
It says I have missing dictionaries for en_US. When I click "Install missing dictionaries", nothing happens:
![Screenshot_20230406_222131](https://user-images.githubusercontent.com/4298614/230546288-dd39b7c8-f3fe-4ca1-8275-f00dadba9e64.png)

**Comment by Geremia** [comment]
@mike-fabian  I figured it out. I needed hunspell-en.

**Comment by mike-fabian** [comment]
> @mike-fabian I figured it out. I needed hunspell-en.

Yes, that's right! The "Install missing dictionaries" button works only on some distributions like openSUSE and Fedora. For Slackware and other distributions I would need extra code because installation of packages works differently. I would be happy for contributions for this.
