### ISSUE TITLE
continuous (enter key) -while-pasting

### ISSUE THREAD

**Issue by sumeetswaroop** [mike-fabian/ibus-typing-booster#438]
**bug**
continuous (enter key) -while-pasting multi-line custom shortcuts 

**Expected behavior**
The cursor should stop at the end of pasted content. (Enter is being pressed)
OR BETTER 
Input method should be paste instead of typing. 

**Screenshots**
[cotinuous-enter-input-while-pasting.webm](https://user-images.githubusercontent.com/130192864/230695342-668e188b-62e0-4503-8566-6c368b7c1229.webm)

**ibus-typing-booster version?**
2.18.9

**Distribution and version?**
Ubuntu 20.10

**Desktop and version?**
GNOME

**Xorg or Wayland?**
Wayland

"Multi-line custom shortcuts"  will greatly enhance the program.

**Comment by mike-fabian** [comment]
OK, this  happens only on Gnome Wayland, on Gnome Xorg it works fine.

I think Wayland has some problem with forward key event.

I’ll check what I can do to solve the problem for Wayland.

**Comment by mike-fabian** [comment]
I introduced, committing multi-line strings line by line with forwarding a key event for the new lines in between here:

https://github.com/mike-fabian/ibus-typing-booster/commit/35a22dab25be8cb9d09d048ca111f661d6b73909

As I describe in the commit message, this was a workaround for the GMail editor in Firefox and for Thunderbird.

One can disable that feature by checking the option 

☑️ Avoid using the forward_key_event() function

But that has other disadvantages, so I do not recommend checking that option until absolutely necessary.

I just checked that the bug in the GMail editor in Firefox still exists (I did not yet check Thunderbird).

**Comment by mike-fabian** [comment]
Included in https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.22.3

**Comment by mike-fabian** [comment]
This makes multi line shortcuts mostly work on Wayland, except in the GMail editor when using firefox, for that case the workaround to commit each line separately and forward a return key event in between is unfortunately still necessary. If you want that working as well I recommend to use Gnome on Xorg.
