### ISSUE TITLE
Please consider removing Microphone Stream to Google from core features

### ISSUE THREAD

**Issue by Jibec** [mike-fabian/ibus-typing-booster#45]
Including in an "input system" a cloud service sending data to google makes me feel really uncomfortable.
If would feel better to see it included as an explicitly external plugin than in core...

https://github.com/mike-fabian/ibus-typing-booster/blob/9594f46caa5d25b2184f0b19163e2d1c30889c3b/ChangeLog#L11
https://github.com/mike-fabian/ibus-typing-booster/blob/9594f46caa5d25b2184f0b19163e2d1c30889c3b/engine/itb_util.py#L3476

**Comment by mike-fabian** [comment]
There is no danger sendng anything accidentally to Google.

1) The speech recognition is disabled completely if there is no key binding for
    the speech recognition command. See the "key bindings" tab in the setup tool.
    By default, this key binding is  empty, then the _speech_recognition() method
    in hunspell_table.py can never be called.
2) In the speech recognition tab, you have to specify the .json file containing your
    Google application credentials. If you don't do that, the _speech_recognition()  method
    immediately returns with an error without trying to record any sound. So even if
    you add a key binding for the speech_recognition command, it still won't do
    anything unless you also do the setup on the Google side as explained in
     http://mike-fabian.github.io/ibus-typing-booster/documentation.html#speech-recognition

By default there is neither a key binding nor a .json file. So this feature is off by default.

If you setup everything to use this feature and want to temporarily disable it, you can
just remove the key binding for the speech_recognition command again.

**Comment by Jibec** [comment]
well, for the moment it is not enable by default, but can be at any moment because of a feature request or a bug.
Unfortunately, both happens quite often.

**Comment by mike-fabian** [comment]
Even if the key binding was set by default, you would still need to do the setup to get your google credentials .json file. 

I will add more Speech recognition services, including services running locally like Pocketsphinx.

Then, the "Speech recognition" tab will get a combo box to select the service one wants to use.
And that combo box will also get an entry "Speech recognition disabled". And I will make that entry the default.

**Comment by Jibec** [comment]
following our Flock discussion, let's close this.
