### ISSUE TITLE
In WhatsApp and Telegram (used in Firefox)  in the middle of the message, when a new word is being started, the first character disappears 

### ISSUE THREAD

**Issue by mike-fabian** [mike-fabian/ibus-typing-booster#473]
While the initial `É` problem is fixed, Mike, from time to time, again on Firefox Web WhatsApp, in the middle of the message, when a new word is being started, the first character disappears. 

That occurs with not accented first characters, and I have not, until now, devised a systematic way of reproducing the issue. 

The issue does not occur when using Chrome.

_Originally posted by @psads-git in https://github.com/mike-fabian/ibus-typing-booster/issues/471#issuecomment-1845442219_

**Comment by mike-fabian** [comment]
Happens even more often on Telegram.

**Comment by mike-fabian** [comment]
Video using WhatsApp:
https://github.com/mike-fabian/ibus-typing-booster/issues/471#issuecomment-1845542884

**Comment by psads-git** [comment]
It appears that some randomness commands the occurrence of the issue, Mike: Sometimes, it occurs very often while writing a same message.

**Comment by mike-fabian** [comment]
I think I have a fix/workaround. 

My current fix/workaround is already an improvement, the first character of a new word now never seems to vanish in WhatsApp and Telegram when using in Firefox.

**But**, when the input becomes empty after a commit and a prediction should appear because the option 

```
Minimum numbers of chars for completion  [   0]
```

is used (The problem reported here seems to occur **only** when that option is used), then sometimes that prediction does not appear. 

That is already much better then when first characters of new words disappear, with my current fix/workaround, one sometimes does not get a prediction when there should be one, that is not nice but not as bad as a typed character disappearing.

**Comment by mike-fabian** [comment]
Video showing the remaining problem in Telegram. About every second time, the prediction which should appear when the input is empty does not appear. It is not **exactly** every second time, just on the average about every second time: 

https://github.com/mike-fabian/ibus-typing-booster/assets/2330175/39de3cec-ad5c-4684-97a3-ae0d0c85a71f

**Comment by psads-git** [comment]
Yes, I agree with you that the workaround, although not the best solution, is much better than the current _status quo_.

Maybe, another workaround is to pass that option from 0 to 1.

**Comment by psads-git** [comment]
Yet, another workaround is to use Chrome instead of Firefox! ;-)

**Comment by mike-fabian** [comment]
> Yes, I agree with you that the workaround, although not the best solution, is much better than the current _status quo_.
> 
> Maybe, another workaround is to pass that option from 0 to 1.

But we want to be able to continue to use 0 for that option.

**Comment by mike-fabian** [comment]
Now I have improved my workaround to also show the predictions on empty input always when they should be shown.
Test builds for ibus-typing-booster-2.24.6 are here: 

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/

**Comment by mike-fabian** [comment]
Seems to work with ibus-typing-booster-2.24.6: 

https://github.com/mike-fabian/ibus-typing-booster/assets/2330175/9492e152-361c-4e8b-ab5c-d335c7875172

**Comment by psads-git** [comment]
Thanks, Mike. It appears that it is working properly, but, maybe, we should wait for longer to make sure the issues does not reappear.

**Comment by psads-git** [comment]
There is an innocuous side-effect: The suggested word is repeated in `gedit`, Mike. That does not affect the usability of `ibus-typing-booster` at all. 

Please, see the attached video.

https://github.com/mike-fabian/ibus-typing-booster/assets/75945439/cb87c81f-27ef-48d7-bb74-08843b462df8

**Comment by mike-fabian** [comment]
You mean this temporary duplication of the word `uma` here?:

![Screenshot](https://github.com/mike-fabian/ibus-typing-booster/assets/2330175/721c9c43-829b-4617-9e59-4164cba98045)

**Comment by psads-git** [comment]
Yes, Mike. That is innocuous though.

**Comment by psads-git** [comment]
That is really an intricate problem, Mike! Personally, I do not mind the duplicated `umauma`.

**Comment by mike-fabian** [comment]
Even with `Minimum chars for completion [   1]` the old  preedit is sometimes visible for a short moment after committing with space. Although in that case it is extremely short, the only work which is done in that case after the commit is the recording to the user database which is very fast. So it is not very obvious and sometimes even fast enough to be invisible.

But predicting the next word when using `Minimum chars for completion [   0]` is more work and takes long enough that the lingering of the old preedit is often quite clearly visible.

**Comment by mike-fabian** [comment]
> That is really an intricate problem, Mike! Personally, I do not mind the duplicated `umauma`.

Yes, I think if I only have the choice between loosing characters or reversing order in some applications and some visual distraction by a preedit which stays too long, I choose the visual distraction. 

Better some visual distraction which does not harm other than hurt the eyes than a clearly wrong result.

If I could make the prediction of the next word faster, this would become less visible. But looking at the code to predict the next word, I see no obvious way to make it faster.

**Comment by mike-fabian** [comment]
Fix included in https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.24.10in
