### ISSUE TITLE
[Feature request] Multi-word suggestions

### ISSUE THREAD

**Issue by Salvatos** [mike-fabian/ibus-typing-booster#49]
From my testing so far, it seems that IBT only suggests single words. It would be extremely useful (for my use case anyway) if it suggested frequent phrases as well, for example:
- Typing 'mob' would suggest 'mobile', but also 'mobile device';
- Typing 'sub' would suggest 'subject', but also 'subject to credit approval';
- Typing 'Gr' would suggest 'Greetings', but also 'Greetings from the Acme Company!';
- And so on.

I found out tonight that one could add shortcuts for such phrases in the configuration panel, but it would be a much more powerful feature if IBT learned them as I type (or from my corpus) instead of having to manually set shortcuts that I then need to memorize.

**Comment by mike-fabian** [comment]
There is another way already to do this manually in addition to  adding  custom shortcuts in the  configuration panel:

If  you type “mobile device”, when you type a regular space after "mobile",  the word mobile is committed. But if you type AltGr+Space, the space goes into the preëdit and you can continue typing "device" and then, when you type a space after typing "device", the text "mobile device" is added  as one  unit to  the user database.
You also can do this with longer texts  like “Greetings from the Acme Company!”.

I have already implemented a new  feature which makes  this automatic for 2-word combinations  like "mobile device". With the new feature, when you type something  like “Greetings from the Acme Company”, not only the single words “Greetings”, “from”, “the”, “Acme”, “Company” are added to the user database but also the 2-word combinations “Greetings from”, “from the”, “the  Acme”, and “Acme Company”. After testing this for a few weeks, I feel that it is very helpful and I will include it in 2.6.0 which I will release very soon (in a few days).

**Comment by mike-fabian** [comment]
Automatic multi word suggestion as described in  my last comment are included in this branch: 

https://github.com/mike-fabian/ibus-typing-booster/tree/release-2.6.0-rc1

You can test this branch if you like. I will release this soon after a bit more testing.

**Comment by mike-fabian** [comment]
After  testing rc1 for a while I found a small problem and  added another patch. Here  is rc2:

https://github.com/mike-fabian/ibus-typing-booster/tree/release-2.6.0-rc2

The new  patch included does  this:

- When Left or BackSpace trigger a commit, forward Left events only when no candidate was selected (i.e. the preëdit was committed)
