### ISSUE TITLE
Tests cost so long that buildvm terminates it

### ISSUE THREAD

**Issue by marguerite** [mike-fabian/ibus-typing-booster#50]
<pre>
[   47s] + pushd engine
[   47s] ~/rpmbuild/BUILD/ibus-typing-booster-2.5.1/engine ~/rpmbuild/BUILD/ibus-typing-booster-2.5.1
[   47s] + python3 hunspell_suggest.py
[   47s] Unable to init server: Could not connect: Connection refused
[   47s] Unable to init server: Could not connect: Connection refused
[  336s] get_hunspell_dictionary_wordlist(): /usr/share/hunspell/de_DE.dic file found.
[  336s] get_hunspell_dictionary_wordlist(): dictionary encoding=ISO8859-1 found in /usr/share/hunspell/de_DE.aff
[  336s] get_hunspell_dictionary_wordlist(): Successfully loaded /usr/share/hunspell/de_DE.dic using ISO8859-1 encoding.
[  336s] get_hunspell_dictionary_wordlist(): /usr/share/hunspell/cs_CZ.dic file found.
[  336s] get_hunspell_dictionary_wordlist(): dictionary encoding=ISO8859-2 found in /usr/share/hunspell/cs_CZ.aff
[  336s] get_hunspell_dictionary_wordlist(): Successfully loaded /usr/share/hunspell/cs_CZ.dic using ISO8859-2 encoding.
[  336s] get_hunspell_dictionary_wordlist(): /usr/share/hunspell/it_IT.dic file found.
[  336s] get_hunspell_dictionary_wordlist(): dictionary encoding=ISO8859-15 found in /usr/share/hunspell/it_IT.aff
[  336s] get_hunspell_dictionary_wordlist(): Successfully loaded /usr/share/hunspell/it_IT.dic using ISO8859-15 encoding.
[  336s] get_hunspell_dictionary_wordlist(): /usr/share/hunspell/es_ES.dic file found.
[  336s] get_hunspell_dictionary_wordlist(): dictionary encoding=UTF-8 found in /usr/share/hunspell/es_ES.aff
[  336s] get_hunspell_dictionary_wordlist(): Successfully loaded /usr/share/hunspell/es_ES.dic using UTF-8 encoding.
[  336s]          17018157 function calls (17017714 primitive calls) in 288.625 seconds
[  336s] 
[  336s]    Ordered by: cumulative time
[  336s]    List reduced from 598 to 12 due to restriction <'hunspell'>
[  336s] 
[  336s]    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
[  336s]         3    0.000    0.000  224.189   74.730 hunspell_suggest.py:117(__init__)
[  336s]         3    0.000    0.000  224.189   74.730 hunspell_suggest.py:136(init_dictionaries)
[  336s]         4    0.000    0.000  224.189   56.047 hunspell_suggest.py:57(__init__)
[  336s]         4    4.988    1.247  224.189   56.047 hunspell_suggest.py:71(load_dictionary)
[  336s]         4    5.181    1.295  155.309   38.827 hunspell_suggest.py:96(<listcomp>)
[  336s]        11    0.007    0.001   63.858    5.805 hunspell_suggest.py:186(suggest)
[  336s]        18   30.868    1.715   61.334    3.407 hunspell_suggest.py:279(<listcomp>)
[  336s]         4    0.001    0.000   58.700   14.675 itb_util.py:2957(get_hunspell_dictionary_wordlist)
[  336s]         4    0.000    0.000    0.002    0.000 itb_util.py:2922(find_hunspell_dictionary)
[  336s]        54    0.001    0.000    0.001    0.000 hunspell_suggest.py:375(<lambda>)
[  336s]        19    0.001    0.000    0.001    0.000 hunspell_suggest.py:311(<listcomp>)
[  336s]        19    0.000    0.000    0.000    0.000 hunspell_suggest.py:317(<listcomp>)
[  336s] 
[  336s] 
[  336s]          17018157 function calls (17017714 primitive calls) in 288.625 seconds
[  336s] 
[  336s]    Ordered by: cumulative time
[  336s]    List reduced from 598 to 4 due to restriction <'enchant'>
[  336s] 
[  336s]    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
[  336s]        19    2.462    0.130    2.463    0.130 _enchant.py:259(dict_suggest)
[  336s]        19    0.009    0.000    0.009    0.000 _enchant.py:253(dict_check)
[  336s]         4    0.000    0.000    0.001    0.000 _enchant.py:330(dict_describe)
[  336s]         4    0.000    0.000    0.001    0.000 _enchant.py:331(cbfunc1)
[  336s] 
[  336s] 
[  336s] + python3 m17n_translit.py
[  336s] + python3 itb_emoji.py
[  336s] Unable to init server: Could not connect: Connection refused
[  337s] Unable to init server: Could not connect: Connection refused
[ 5747s] qemu-system-x86_64: terminating on signal 15 from pid 1186 (<unknown process>)

Job seems to be stuck here, killed. (after 5400 seconds of inactivity)
</pre>

@mike-fabian 

Hi, I see you directly maintain the package for openSUSE, but unluckily tests always fail on OBS, especially the engines part.

There're four tests, each costs 280+ seconds to finish, so OBS thought the job stuck and killed it.

Can you improve the time or find a way to prevent the job being killed?

Greetings

Marguerite

**Comment by mike-fabian** [comment]
I have no idea how to make that faster, maybe it is best if I do the same you did and disable these tests in the SuSE .spec file when I release the next version.

**Comment by marguerite** [comment]
@mike-fabian my fix was temporary, I would like to have a look at “_constraints” file of OBS this week, see if we can ask more resources for the build virtual machine instance.

It there any way we can run those four tests simultaneously? Resources like memory can be increased via that constraints file. So if we run it simultaneously, then build/check time will decreases a lot

**Comment by mike-fabian** [comment]
The test which takes really long is 

    python3 itb_emoji.py

Currently it does not produce any output while it runs unless it fails.
Maybe it would help if it continuously produces some output while it runs by starting it with the verbose option?:

   python3 itb_emoji -v

**Comment by marguerite** [comment]
@mike-fabian

I did it this way:

create a .sh file at build time 

run these four ‘python3 xx.py &’ tests in background in a for loop.

then “wait” and exit from the.sh file 

So the longest time and the total time is now ‘python3 itb_emoji.rb’. It takes 9min, and other tests will reflush the stdout during this 9 min. OBS is now happy.

One trade-off here is that if build fails, the error message may be a little complicated. But it’s still debug-able 

BTW, having output is also a good way, but really it takes too much time testing compared with its build time

**Comment by marguerite** [comment]
https://build.opensuse.org/request/show/680065

**Comment by mike-fabian** [comment]
Thank you!

**Comment by mike-fabian** [comment]
It doesn’t really seem to help though, I still see the build jobs terminated with:

Job seems to be stuck here, killed. (after 5400 seconds of inactivity)

**Comment by mike-fabian** [comment]
It mostly seems to work though, I’ll close this for now.
