### ISSUE TITLE
can not found any spell checking dictionary

### ISSUE THREAD

**Issue by jakbin** [mike-fabian/ibus-typing-booster#503]
**Describe the bug**
i can not found any spell checking dictionary(Hindi).

**To Reproduce**
1. I just open ibus-typing-booster setup. and i can not any spell checking dictionary not found(Hindi).

**Expected behavior**
in documentation , you shown hindi spell checking dictionary (https://mike-fabian.github.io/ibus-typing-booster/docs/user/#2)

**Screenshots or videos**
![typing-booster](https://github.com/mike-fabian/ibus-typing-booster/assets/65591973/51b5edd7-ec94-41d3-bc5b-1c86379035f6)

**ibus-typing-booster version?**
Open the ibus-typing-booster setup tool and click on the `About` button (Or check the version of the installed package, for example using `rpm -q ibus-typing-booster` on rpm based distribtions).

**ibus version?**
IBus 1.5.29-rc2

**Distribution and version?**
IBus 1.5.29-rc2

**Desktop and version?**
XFCE 4.18

**Xorg or Wayland?**
x11

**Comment by mike-fabian** [comment]
What distribution are you using?
Does the dictionary file in the directory `/usr/share/hunspell/hi_IN.dic` exist?

On fedora, you need to install the `hunspell-hi` package.

On other distributions the package name might be different and it might be in a different directory.

ibus-typing-booster searches in several directories, if it is in a different directory on your distribution, I need to add it to the search list.

**Comment by jakbin** [comment]
It's debian based kali linux with xfce

**Comment by jakbin** [comment]
i have fix this problem by installing `hunspell-hi` package. But how use my custom dictionary for this ??

**Comment by mike-fabian** [comment]
ibus-typing-booster looks for data files first in `user_datadir`, for example when searching for dictionaries:

https://github.com/mike-fabian/ibus-typing-booster/blob/main/engine/itb_util.py#L3334

**Comment by mike-fabian** [comment]
```
user_datadir = xdg_save_data_path('ibus-typing-booster/data')
 ```

**Comment by mike-fabian** [comment]
https://github.com/mike-fabian/ibus-typing-booster/blob/main/engine/itb_util.py#L5170

**Comment by mike-fabian** [comment]
So `user_datadir` is usually `~/.local/share/ibus-typing-booster/data`.

Create that directory if it does not exist.

Put your customized `hi_IN.dic` into that directory.

Then your customized dictionary will be preferred.

**Comment by jakbin** [comment]
Great, thanks for reply. I will try it.

**Comment by jakbin** [comment]
Yes, it works for me .

**Comment by mike-fabian** [comment]
> Yes, it works for me .

Thank you very much, than I can close this issue.
