### ISSUE TITLE
[BUG] Gnome Wayland, Fedora 40: Gnome keyboard shortcuts don’t work when Typing Booster has focus

### ISSUE THREAD

**Issue by mike-fabian** [mike-fabian/ibus-typing-booster#507]
Originally reported here: https://bugzilla.redhat.com/show_bug.cgi?id=2272023

Fix attempt by Takao Fujiwara (Thank you very much!):
https://src.fedoraproject.org/rpms/ibus-typing-booster/pull-request/39#request_diff

**Comment by mike-fabian** [comment]
Doesn’t happen in Fedora 39 with:

```
mutter-45.5-1.fc39.x86_64
gnome-shell-45.5-1.fc39.x86_64
```

**Comment by mike-fabian** [comment]
The attempted fix in https://src.fedoraproject.org/rpms/ibus-typing-booster/pull-request/39#request_diff is unfortunately not sufficient because this does not only happen with Gnome keyboard shortcuts involving `Super` (`Mod4`) but with **any** Gnome keyboard shortcuts.

For example, “Move window” is by default set to `Alt+F7` and when ibus-typing-booster has keyboard focus, this does not work either unless the `☑️ Avoid using the forward_key_event() function` option is used.

![Screenshot](https://github.com/mike-fabian/ibus-typing-booster/assets/2330175/411894bb-7d97-47e7-8705-8dfc88f325f4)

**Comment by fujiwarat** [comment]
Current my patch checks key.mod4 only but probably that API needs to return `False` with other modifier keys.
I.e. if ibus-typing-booster manages Alt-F7 shortcut key with a customized shortcut key, it should be handled before the API is called.

**Comment by mike-fabian** [comment]
> Current my patch checks `key.mod4` only but probably that API needs to return `False` with other modifier keys.
> I.e. if ibus-typing-booster manages Alt-F7 shortcut key with a customized shortcut key, it should be handled before the API is called.

Yes, I think so too.

**Comment by mike-fabian** [comment]
Surprisingly, Gnome keyboard shortcuts without modifiers like `F7` work even when the key is forwarded using `forward_key_event()`. Only when a modifier is involved (`Shift+F7`, `Control+F7`, `Alt+F7`, `Super+F7`,...) the Gnome keyboard shortcut does not work when ibus-typing-booster forwards the key event using `forward_key_event()`.
