### ISSUE TITLE
Building on Ubuntu 19.04 results in Nothing

### ISSUE THREAD

**Issue by joe247** [mike-fabian/ibus-typing-booster#52]
Firstly, I really thank you for doing this project, I love python & I wish to contribute _(but I don't know how to, I'm an intermediate)_. I didn't want to bother you with this, but couldn't help running into an issue. Please help.

I'm trying to install ibus-typing-booster for Hindi:

- I downloaded the source from https://github.com/mike-fabian/ibus-typing-booster/archive/2.6.4.zip

- Then checked & satisfied all dependencies: `ibus >= 1.5.3, libm17n-0, m17n-db, python3 >= 3.3, python3-dbus, python3-xdg` as mensioned [here](https://askubuntu.com/a/913161/929199).

- Finally executed the commands:
```
./autogen.sh
./configure --prefix=/usr --libexecdir=/usr/lib/ibus
make
make check
make install
```

- Here is the [build output](http://p.ip.fi/96W1). *Everything **seems** ok*

------

**Issue**

But I cannot see the `ibus-typing-booster` preferences in the Applications, all that is new is an [emoji picker](https://imgur.com/a/l9OSOvs)

I rebooted the system and tried to get [this (Typing Booster)](https://www.2daygeek.com/wp-content/uploads/2017/04/install-ibus-typing-booster-in-linux-5.png) or [this (Hunspell)](https://dann3217.files.wordpress.com/2013/05/wp_post_typingbooster_inputsources.jpg?w=584&h=396) but instead got [this](https://imgur.com/a/0inpRze), none of which give suggestions while typing.

[My system info](http://p.ip.fi/AO8Y), [ibus info](http://p.ip.fi/yhVg)

 >What is missing?

------

**Footnote**

The command `make test` had failed, the test-suit.log showed some `Traceback Error`, I did something then (which I don't remember now) and then the command did not fail.

**Comment by joe247** [comment]
I ran the same on elementary os, but on `make check` command i got [`Test Fail`](http://p.ip.fi/CmR4).
So I went the check the log given in the output [tests/test-suite.log](http://p.ip.fi/mxws)
It says `Settings schema 'org.freedesktop.ibus.engine.typing-booster' is not installed`, but that's what I'm trying to install right?

Where am I going wrong?

**Comment by mike-fabian** [comment]
The screenshots you showed, i.e. [this](https://www.2daygeek.com/wp-content/uploads/2017/04/install-ibus-typing-booster-in-linux-5.png) and [this](https://dann3217.files.wordpress.com/2013/05/wp_post_typingbooster_inputsources.jpg?w=584&h=396) are apparently for very old versions  of typing-booster.

Current versions of typing-booster don’t have many different engines for different languages, there is just one engine which can be configured to work for many languages.

So there is no “Tamil (Tamil - IN (Typing Booster))” or “English (English - US (Hunspell))” anymore, these were the engines only for Tamil and  only for English.

Now you should find something like “Other (Typing Booster)” in the “Other” section of adding input methods to the Gnome desktop.

How you can add typing booster to your desktop is explained with screenshots for several desktops here:

[Adding ibus-typing-booster to your desktop](http://mike-fabian.github.io/ibus-typing-booster/documentation.html#adding-to-desktop)

Does that work for you? Can you find “Other (Typing Booster)”?

**Comment by joe247** [comment]
Thank you, very much I did exactly as you told and here is the result: https://imgur.com/a/U4ThmmD.
> I ran the same on elementary os, but on `make check` command i got [`Test Fail`](http://p.ip.fi/CmR4).
> So I went the check the log given in the output [tests/test-suite.log](http://p.ip.fi/mxws)
> It says `Settings schema 'org.freedesktop.ibus.engine.typing-booster' is not installed`, but that's what I'm trying to install right?
> 
> Where am I going wrong?

So this time in Elementary I tried with a fresh download, this time the `tests/test-suit.log` says:
```
=====================================================
   ibus-typing-booster 2.6.4: tests/test-suite.log
=====================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: run_tests
===============

Traceback (most recent call last):
  File "./run_tests", line 24, in <module>
    from gi import require_version
ModuleNotFoundError: No module named 'gi'
FAIL run_tests (exit status: 1)
```
But I have no problems importing `gi` in both  python2 & python3 directly (I have deactivated the conda environment). How should I proceed?

**Comment by mike-fabian** [comment]
> But I have no problems importing `gi` in both python2 & python3 directly (I have deactivated the conda environment). How should I proceed?

Your screenshot seems to show that it works. And apparently you were able to open the setup tool and do some setup.

ibus-typing-booster uses the line

```
from gi import require_version
```

in several files, also in the setup tool:

https://github.com/mike-fabian/ibus-typing-booster/blob/master/setup/main.py#L37

If that didn’t work, you would not be able to  run the setup tool

The same line is also used in the code for the engine:

https://github.com/mike-fabian/ibus-typing-booster/blob/master/setup/main.py#L37

(not only there, in several other files as well).

you would not be able to type using ibus-typing-booster, if that line
didn’t work.

But apparently it is working for you.

I am puzzled why it fails for you when running the tests.
Maybe something was lacking on your system when you were running "make check" which
is available now?

If you go to the source code directory and run "make check" again now, does it still
fail?

**Comment by joe247** [comment]
My apologies for the ambiguity.

I have two system at home:
1. Ubuntu on Desktop
2. Elementary OS on Laptop

The screenshots belongs to Ubuntu in which everything is working perfectly fine. The typing booster runs well.
>Maybe something was lacking on your system when you were running "make check" which
is available now?

`make check` no longer fails for Ubuntu.

---

Now, I'm trying to  build Typing Booster on Elementary OS. I've fulfilled the requirements, but as said:
>If you go to the source code directory and run "make check" again now, does it still
fail?

Yes, it fails.
>But I have no problems importing gi in both python2 & python3 directly (I have deactivated the conda environment).

Which is true about Elementary OS.

**Comment by mike-fabian** [comment]
I haven’t heard of Elementary OS yet. 

Do you mean “from gi import require_version" works for you in Elementary OS?
Or just "import gi"?

**Comment by joe247** [comment]
>Do you mean “from gi import require_version" works for you in Elementary OS?
Or just "import gi"?
```
(base) joe@eOS:~$ conda deactivate
joe@eOS:~$ python
Python 2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi import require_version
>>> exit()
joe@eOS:~$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi import require_version
>>> import gi
>>> exit()
joe@eOS:~$ python
Python 2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> exit()
joe@eOS:~$
```

Both works in [Elementary OS](https://elementary.io/)

**Comment by mike-fabian** [comment]
Only Python3 is interesting for ibus-typing-booster.

**Comment by mike-fabian** [comment]
I tried myself by installing  elementaryos-5.0-stable.20181016.iso into a vm.

I installed the following extra stuff:

```
sudo apt install pkg-config
sudo apt install ibus
sudo apt install python3-dev
sudo apt install libibus-1.0-dev
```

Then I downloaded the latest ibus-typing-booster release:

```
wget https://github.com/mike-fabian/ibus-typing-booster/releases/download/2.6.5/ibus-typing-booster-2.6.5.tar.gz
```

Then:

```
tar xvf ibus-typing-booster-2.6.5.tar.gz
cd ibus-typing-booster-2.6.5
./configure --prefix=/usr --libexec=/usr/lib/ibus
make
sudo make install
make check
```

No errors in "make check", it runs just fine.

Then I used "ibus-setup" to add typing-booster.

I can switch input methods with the default Control+Space key.
And I can type with ibus-typing-booster.
And bring up the setup tool of ibus-typing-booster with the default
key binding Mod5+F10 (Mod5 is the right Alt key) and by starting it directly
with:

```
/usr/lib/ibus/ibus-setup-typing-booster
```

So everything works fine for me.

**Comment by mike-fabian** [comment]
![ibus-typing-booster-elementary-os-juno](https://user-images.githubusercontent.com/2330175/64475162-3a428300-d17f-11e9-9494-b602b56a3c0a.png)

This is how it looks for me in elementary os juno.

**Comment by joe247** [comment]
Okay, so I ran:
```
wget https://github.com/mike-fabian/ibus-typing-booster/releases/download/2.6.5/ibus-typing-booster-2.6.5.tar.gz

tar xvf ibus-typing-booster-2.6.5.tar.gz
cd ibus-typing-booster-2.6.5
./configure --prefix=/usr --libexec=/usr/lib/ibus
make
sudo make install
```
This time without `./autogen.sh` and with `sudo` in `sudo make check` command, and I ran into error. The [test-suit.log](http://p.ip.fi/8AFi) is too long to post directly.
But this time it's different, I think some dictionary configurations are wrong, is it?

**Comment by mike-fabian** [comment]
From your test-suite.log:

```
======================================================================
FAIL: test_accent_insensitive_matching_german_database (test_itb.ItbTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joe/ibus-typing-booster-2.6.5/tests/test_itb.py", line 498, in test_accent_insensitive_matching_german_database
    'Glühwürmchen')
AssertionError: '☹  dictionary not found. Please install hunspell dictionary!' != 'Glühwürmchen'
- ☹  dictionary not found. Please install hunspell dictionary!
+ Glühwürmchen
```

This is most likely because you don‘t have the German hunspell dictionary installed.
The test cases need several dictionaries, one of them is the German dictionary.

In case of Ubuntu/Elementary OS, it is in this package:

```
mfabian@elementaryos:~/ibus-typing-booster-2.6.5$ apt-file search /usr/share/hunspell/de_DE.dic
hunspell-de-de: /usr/share/hunspell/de_DE.dic
hunspell-de-de-frami: /usr/share/hunspell/de_DE.dic
mfabian@elementaryos:~/ibus-typing-booster-2.6.5$ 
```

**Comment by mike-fabian** [comment]
> By the way I have written a small [article](https://medium.com/@jovial7joe33/type-in-your-tongue-in-linux-58bc55978e93) on how to install Typing Booster on Ubuntu.

Thank you!

Your article contains:

> Mike Fabian started his project in 2010. Along with Anish Patil they have come a long way.

Actually I joined this project in 2012. Anish started it in 2010.

**Comment by mike-fabian** [comment]
By the way, your screenshot  shows an interesting  list of languages:
English, Hindi, Marathi, Greek, and Hebrew. 
Do  you speak all of these?

**Comment by joe247** [comment]
> Actually I joined this project in 2012. Anish started it in 2010.

I corrected it.

---

I had some issues installing the Hunspell German dictionary (some package conflicts) so I remove Hunspell completely.
Then installed just the dictionaries I probably will use:
en_us -> Engilsh US,
en_gb -> Engilsh UK,
hi_in -> Hindi,
ml_in -> Malayalam,
el_gr -> Greek and
he_il -> Hebrew

Then, I ran `make test`, so just as pointed log asked for German dictionary (de_de), I installed it.
Again I ran `make test`, this time asked for a French dictionary (fr_fr), but Hunspell only provides (fr (dependency)) and (fr-classical) , I installed them.
Again, this time it asked for, I guess Marathi Dictionary:
```
TabSqliteDb.select_words() hunspell: best_candidates=[('☹ mr_IN dictionary not found. Please install hunspell dictionary!', 0)]
```
But there is no such Hunspell dictionary available 🤨?
Can you provide a list of dictionaries required for test cases?

And I was searching through the log with this ☹ emoji :)
Can the log be made more comprehensive?

---

>By the way, your screenshot shows an interesting list of languages:
English, Hindi, Marathi, Greek, and Hebrew.
Do you speak all of these?

I speak English, Hindi and Malayalam (it's ml_IN in the screenshot).
Dad's studying theology, so he requires other two, Greek and Hebrew.

**Comment by joe247** [comment]
> Can you provide a list of dictionaries required for test cases?

I just went through  `ibus-typing-booster/tests/test_itb.py`

Found:
```python
...
def test_complete_word_from_us_english_dictionary(self):
        self.engine.set_current_imes(['NoIME', 't-latn-post'])
        self.engine.set_dictionary_names(['en_US'])
...
def test_marathi_and_britisch_english(self):
        self.engine.set_current_imes(['mr-itrans', 'NoIME'])
        self.engine.set_dictionary_names(['mr_IN', 'en_GB'])
...
def test_korean(self):
        if not itb_util.get_hunspell_dictionary_wordlist('ko_KR')[0]:
            # No Korean dictionary file could be found, skip this
            # test.  On some systems, like 'Arch' or 'FreeBSD', there
            # is no ko_KR.dic hunspell dictionary available, therefore
            # there is no way to run this test on these systems.
            # On systems where a Korean hunspell dictionary is available,
            # make sure it is installed to make this test case run.
            # In the ibus-typing-booster.spec file for Fedora,
            # I have a “BuildRequires:  hunspell-ko” for that purpose
            # to make sure this test runs when building the rpm package.
            return
        self.engine.set_current_imes(['ko-romaja'])
        self.engine.set_dictionary_names(['ko_KR'])
...
def test_accent_insensitive_matching_german_dictionary(self):
        self.engine.set_current_imes(['NoIME', 't-latn-post'])
        self.engine.set_dictionary_names(['de_DE'])
...
def test_accent_insensitive_matching_french_dictionary(self):
        self.engine.set_current_imes(['NoIME', 't-latn-post'])
        self.engine.set_dictionary_names(['fr_FR'])
...
def test_digits_used_in_keybindings(self):
        self.engine.set_current_imes(['hi-itrans'])
        self.engine.set_dictionary_names(['hi_IN'])
...
def test_sinhala_wijesekera(self):
        self.engine.set_current_imes(['si-wijesekera', 'NoIME'])
        self.engine.set_dictionary_names(['en_US'])
```

Okay, so what you did with Korean dictionary, may also be done with others.
Also instead of directly skipping a test, put up a warning, saying:  `[xy_XY] dictionary not found; test not done; may encounter errors during auto-completion!`
And again I couldn't find Hunspell Marathi dictionary.

Thank you.

**Comment by mike-fabian** [comment]
>  I corrected it.

Thank you for correcting the article!

**Comment by mike-fabian** [comment]
> Can you provide a list of dictionaries required for test cases?

I think you found it already in ibus-typing-booster/tests/test_itb.py
Unfortunately not all of them are available on all systems. 
And sometimes the contents are different which also may make some tests fail.

**Comment by joe247** [comment]
I edited the `test_itb.py` as:
```python
...
def test_marathi_and_britisch_english(self):
        if not itb_util.get_hunspell_dictionary_wordlist('mr_IN')[0]:
            return
        self.engine.set_current_imes(['mr-itrans', 'NoIME'])
        self.engine.set_dictionary_names(['mr_IN', 'en_GB'])
...
```
Then did every thing all over again.
But I got some other error:
```
ERROR: test_accent_insensitive_matching_german_database (test_itb.ItbTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joe/Downloads/ibus-typing-booster-2.6.5/tests/test_itb.py", line 499, in test_accent_insensitive_matching_german_database
    self.engine._candidates[0][0]),
IndexError: list index out of range

======================================================================
ERROR: test_emoji_related_tab_enable_cursor_visible_escape (test_itb.ItbTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joe/Downloads/ibus-typing-booster-2.6.5/tests/test_itb.py", line 303, in test_emoji_related_tab_enable_cursor_visible_escape
    self.assertEqual(self.engine._candidates[5][0], '🐫')
IndexError: list index out of range

======================================================================
ERROR: test_emoji_triggered_by_underscore_when_emoji_mode_is_off (test_itb.ItbTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joe/Downloads/ibus-typing-booster-2.6.5/tests/test_itb.py", line 594, in test_emoji_triggered_by_underscore_when_emoji_mode_is_off
    self.assertEqual(False, self.engine._candidates[5][0] == '🐫')
IndexError: list index out of range

----------------------------------------------------------------------
Ran 24 tests in 20.740s

FAILED (errors=3)
FAIL run_tests (exit status: 1)
```
I'm sorry, I couldn't understand (even though I saw the tests in `ibus-typing-booster/tests/test_itb.py` file.

**Comment by mike-fabian** [comment]
test_accent_insensitive_matching_german_database fails because you don’t have the German  Hunspell dictionary.

**Comment by joe247** [comment]
>Then, I ran make test, so just as pointed out the test-suit.log asked for German dictionary (de_de) and I installed it.

I do have.

I also tried all the variants:
hunspell-de-at, hunspell-de-ch, hunspell-de-de (including "frami" version which removes the other package).

```bash
joe@eOS:~$ sudo apt install hunspell-de-ch
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  libreoffice-writer
The following NEW packages will be installed
  hunspell-de-ch
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 284 kB of archives.
After this operation, 1,154 kB of additional disk space will be used.
Get:1 http://in.archive.ubuntu.com/ubuntu bionic/main amd64 hunspell-de-ch all 20161207-4 [284 kB]
Fetched 284 kB in 8s (34.3 kB/s)                                                                          
Selecting previously unselected package hunspell-de-ch.
(Reading database ... 255314 files and directories currently installed.)
Preparing to unpack .../hunspell-de-ch_20161207-4_all.deb ...
Unpacking hunspell-de-ch (20161207-4) ...
Setting up hunspell-de-ch (20161207-4) ...
Processing triggers for postgresql-common (190) ...
supported-versions: WARNING! Unknown distribution: elementary
ubuntu found in ID_LIKE, treating as Ubuntu
supported-versions: WARNING: Unknown Ubuntu release: 5.0
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
  de_at
  de_ch
  de_de
  el_gr
  en_gb
  en_us
  fr
  he_il
  hi_in
  ml_in
Removing obsolete dictionary files:
joe@eOS:~$
```
You see...
Am I doing something wrong?

**Comment by mike-fabian** [comment]
These 3 fails go away when you install python3-echant.

sudo apt install  python3-enchant

**Comment by mike-fabian** [comment]
Does that work for you as well?

**Comment by joe247** [comment]
>These 3 fails go away when you install python3-echant.
sudo apt install python3-enchant
Does that work for you as well?

Yes it does!

>I made a new bug fix release: 
https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.6.6
This includes skipping the test cases for Korean and Marathi if the dictionaries are not available and skipping the test cases using enchant if python3-enchant is not available.

I observed few things:
- Build fails if I don't have `python3-gi` package on Linux.
- If I accidentally `make` the ibus-typing-booster in conda environment it fails with `ModuleNotFoundError: No module named 'gi'` log, so next, I have to run `make clean`, then deactivate the conda environment, finally run all the commands.
- If build fails, a partial [emoji-picker icon](https://imgur.com/H6g9uC6) is created.

Anyway, thank you for helping me out.
