### ISSUE TITLE
[BUG] Changing case following by returns adds RETURN 

### ISSUE THREAD

**Issue by psads-git** [mike-fabian/ibus-typing-booster#558]
Hi, Mike,

When changing the case of a word and then pressing `enter`, `ibus-typing-booster` adds  the word `return`, which is committed if  `space` is pressed.

Please, watch the attached video.

Thanks!

https://github.com/user-attachments/assets/d2c9d723-a00b-474b-bb28-8a08526dd199

**Comment by mike-fabian** [comment]
Thank you, I can reproduce that!

**Comment by mike-fabian** [comment]
I think I have a fix. Test builds for ibus-typing-booster-2.25.7 are at
 https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/

**Comment by psads-git** [comment]
Thanks, Mike! It appears to be working fine! I

**Comment by mike-fabian** [comment]
I released ibus-typing-booster-2.26.8 with this fix: 
https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.26.8
