### ISSUE TITLE
Translation platform migration

### ISSUE THREAD

**Issue by Jibec** [mike-fabian/ibus-typing-booster#56]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks [2]? (this is a setting per component)
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by mike-fabian** [comment]
My development branch is "master".

License of the translation: The same as the source code I guess, i.e. GPLv3+
https://spdx.org/licenses/GPL-3.0-or-later.html 
Does that make sense?
I don’t  think any announcement/warning is needed to display to the translators.
I  am unsure about the checks, looks like  I want most of them. Can I  easily change  this?
I guess automatically detecting translation files is not needed, I think  there is only one file, this one:
https://github.com/mike-fabian/ibus-typing-booster/blob/master/po/ibus-typing-booster.pot

**Comment by mike-fabian** [comment]
I made ibus-typing-booster "master" in zanata readonly now.

**Comment by mike-fabian** [comment]
This is done now, translations can be done using weblate:

https://translate.stg.fedoraproject.org/projects/ibus-typing-booster/app/

Thank you very much!
