### ISSUE TITLE
[ENHANCEMENT] Offer additional engines which do simple ibus-m17n emulation by default

### ISSUE THREAD

**Issue by mike-fabian** [mike-fabian/ibus-typing-booster#570]
typing-booster can already simulate the behaviour of ibus-m17n pretty closely as is described in this chapter of the user documentation:

- Simulate the behaviour of ibus-m17n https://mike-fabian.github.io/ibus-typing-booster/docs/user/#2_2_1_1

This is done by switching off all of the fancy features typing-booster normally offers and restricting it to the basic functionality of m17n transliteration.

But as there is only one  engine at the moment, if one restricts that one  to simple m17n emulation, one looses all the nice features. It is not possible at the moment to have a simple engine doing only m17n transliteration **and** a “normal” engine  with all the nice features at the same time.

Also, as  quite a lot of settings have to be changed to reduce the functionality to m17n emulation, it is not obvious for users how do do that without reading the documentation.

And currently such an engine restricted to m17n emulation cannot be offered by default as it would be silly to restrict the  "normal" typing booster engine by default.

The idea to fix that is to keep the "normal" `typing-booster` engine unchanged und unrestricted and in addition offer separate engines for m17n input methods which are by default restricted to doing only the m17n transliteration. But using the setup tool one can lift the restrictions even for the engines which are restricted by default. This makes it possible to have several fully functional typing booster engine with different settings. 

This could be used to split learning words per language as was requested in this issue: 
https://github.com/mike-fabian/ibus-typing-booster/issues/165 
One could setup one  instance of typing-booster for English and  another one for Slovak and then the words learned are saved to different databases for these languages. Of course that makes it necessary switching engines when switching languages. I think in most cases it is better to use a single typing-booster engine for  multiple languages to save time  by not having to switch engines. But if one really wants different engines  for different languages, that would be possible with  this enhancement.

**Comment by mike-fabian** [comment]
Simple engines to emulate ibus-m17n are available now in the  branch  release-candidate-2.26.21.

Builds for Fedora are available here:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/

This  video shows a comparison of using `hi-itrans` with the “normal” ibus-typing-booster engine where suggestions are shown, with using it in ibus-m17n (`m17n:hi:itrans` “Hindi (hi-itrans (m17n))”) where no suggestions are shown and the typed characters are committed as early as possible. Finally it shows using it with the `tb:hi:itrans` “Hindi (hi-itrans (Typing Booster))” engine which behaves exacly like the respective ibus-m17n engine, no suggestions are shown and the preedit is commited as early as possible:

https://github.com/user-attachments/assets/9714fded-010f-4a3a-95a8-45249e5e9938

**Comment by mike-fabian** [comment]
@psads-git Hi Paul, this new feature which I have implemented is surely not interesting to you as you want to continue  using the “normal” typing booster for the completions. The new engines I implemented here are restricted do doing only simple  transliteration, no  completion, nothing fancy. But to implement this, I had to do a lot of changes all over the code. If I did a good job **nothing at all** should change for you if you update to the newest build from 

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-typing-booster/builds/

(Currently 2.26.26).

If anything changes for you or you notice any problems, please tell me!

**Comment by psads-git** [comment]
Hi Mike,

Thank you for the update. I use ibus-typing-booster daily and quite extensively. If I notice anything wrong after updating, I will definitely let you know.

Best regards,

Paul

**Comment by mike-fabian** [comment]
Documentation for the new feature is in the rewritten chapter

Simulate the behaviour of ibus-m17n: https://mike-fabian.github.io/ibus-typing-booster/docs/user/#2_3

**Comment by psads-git** [comment]
I can confirm, Mike, that `ibus-typing-booster` is working properly and as before.

**Comment by mike-fabian** [comment]
> I can confirm, Mike, that `ibus-typing-booster` is working properly and as before.

Thank you very much!
