### ISSUE TITLE
Test suite doesn’t pass on Arch Linux (different dictionaries path)

### ISSUE THREAD

**Issue by ariasuni** [mike-fabian/ibus-typing-booster#6]
The test suit fails on Arch Linux because dictionaries are either available in `/usr/share/myspell/dicts/` or `/usr/share/hunspell/`. The path is hardcoded both in `engine/hunspell_suggest.py` and in `setup/user_transliteration.py`. Could you make it configurable so that I could set it to a value that works for my distribution?

EDIT: also, the test suite doesn’t run some checks only on openSUSE because there’s no korean myspell dictionary, maybe you can add Arch too (or maybe it’s a hack that shouldn’t be expanded)?

so that, in the file `tests/test_itb.py`, the line:
```python
if 'openSUSE' in str(subprocess.check_output(["lsb_release","-is"])):
```

become:
```python
if str(subprocess.check_output(["lsb_release","-is"]), 'utf-8').strip() \
    in ['openSUSE', 'Arch']:
```

**Comment by mike-fabian** [comment]
I’ll add your hack. Or is there a Korean myspell dictionary oh Arch?

**Comment by mike-fabian** [comment]
On openSUSE:

mfabian@openSUSE-Leap-42:~> python3
Python 3.4.5 (default, Jul 03 2016, 12:57:15) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> str(subprocess.check_output(["lsb_release","-is"]))
"b'openSUSE project\\n'"
>>>

**Comment by mike-fabian** [comment]
Would this work for you on Arch?: 
https://github.com/mike-fabian/ibus-typing-booster/commit/bc4edeee642c9949dd5e63d90e26be2c8d92a61f

**Comment by mike-fabian** [comment]
And yes, I’ll make the path for the dictionaries configurable.

**Comment by ariasuni** [comment]
There’s no Korean dictionary on Arch as far as I know. The code you wrote works on my machine.

But maybe you should test for the presence of the dictionary instead of dealing with a list of distributions, which will never be complete and must be kept up-to-date?

**Comment by mike-fabian** [comment]
Yes, it is probably better to check for the presence of the Korean dictionary.

By the way, where are the hunspell dictionaries located on Arch?

**Comment by ariasuni** [comment]
> By the way, where are the hunspell dictionaries located on Arch?

There are located in `/usr/share/hunspell`.
