### ISSUE TITLE
 how to build the Custom Code Table files for ibus-typing-booster?

### ISSUE THREAD

**Issue by YQ-YSY** [mike-fabian/ibus-typing-booster#60]
Hi! mike-fabian, 
If the option "Use digits as select keys" is disabled, then, maybe my "Code table for Chinese stroke sequence (one hand) input method" can use it. The font is google Noto Sans CJK SC. If possible, Can you tell me how to build the Custom Code Table files for ibus-typing-booster? I want to add my Code table into the data of ibus-typing-booster.

**Comment by mike-fabian** [comment]
ibus-typing-booster does not have code table  files. 

We could continue to work on including your table into ibus-table, I got busy with other stuff and didn't follow up on what we tried there, we could try again.

Or, if you want to  use it with ibus-typing-booster, you  could try to convert your table in
an input method for libm17n. ibus-typing-booster can  use all libm17n input methods.

I am not sure how useful that would be though, Chinese doesn’t separate words by spaces, therefore ibus-typing-booster could not easily separate the input into words to calculate predictions from previous input. That would not be easy to make that work, I am not  sure whether ibus-typing-booster could be useful for typing  Chinese with such a stroke sequence input method. Maybe not. I need to think more about that ...

**Comment by YQ-YSY** [comment]
Thank you for your reply. 
Because I saw the documentation of  ibus-typing-booster said: Here the emoji mode is used to input the CJK radical "turtle". Anything in Unicode except letters is possible. 

So i think maybe I can add my code table to UnicodeData.txt or emoji-data.txt, and then, I can input 3525115 get a single text of Chinese "turtle"(龟),  Unicode is 9F9F. Input 3551.3525115 get the word of Chinese "dark turtle"(乌龟), Unicode is 4E4C and 9F9F. Two texts separate by decimal point. Do you think it is feasible?

I already have single text code table (30,000 texts) and word code table (1,800,000 words). If necessary, I can add Unicode to the code table for every text and every word. If this solution is possible, everyone in the world can type Chinese one stroke by one stroke, Even if he doesn't understand Chinese.

**Comment by mike-fabian** [comment]
No, this does not make any sense at all for ibus-typing-booster. 

As I wrote in my previous comment, it is maybe possible to write an libm17n input method for your table. Then it might be possible to use it with ibus-typing-booster. 

Or one could maybe add it to ibus-table. 

But adding it to UnicodeData.txt or emoji-data.txt makes no sense at all.

I am closing this here.
