### ISSUE TITLE
hunspell dictionary not detect

### ISSUE THREAD

**Issue by khumnath** [mike-fabian/ibus-typing-booster#64]
installed ibus-booster on linux mint.
hunspell-ne is installed on my system
`computebox@computebox:~$ sudo apt install hunspell-ne
Reading package lists... Done
Building dependency tree       
Reading state information... Done
hunspell-ne is already the newest version (1:6.0.3-3).
`
but typing booster predictive suggestion says
**### ☹ ne dictionary not found. Please install hunspell dictionary!
![Screenshot from 2019-12-14 21-10-34](https://user-images.githubusercontent.com/50103558/70848533-52c8e480-1eb6-11ea-8a57-e0414a24dcbb.png)
![Screenshot from 2019-12-14 21-11-10](https://user-images.githubusercontent.com/50103558/70848536-5b211f80-1eb6-11ea-9e1f-55e5a94fb7b3.png)

**

**Comment by mike-fabian** [comment]
Maybe the dictionary is in  ne_NP or ne_IN? On Fedora it is in these files: 
```
$ ls -l /usr/share/myspell/ne_*dic 
lrwxrwxrwx. 1 root root      9  7月 25 18:24 /usr/share/myspell/ne_IN.dic -> ne_NP.dic
-rw-r--r--. 1 root root 876714  7月 25 18:24 /usr/share/myspell/ne_NP.dic
```

**Comment by mike-fabian** [comment]
If the dictionary is in ne_NP or ne_IN, then chose one of these in the setup tool.

ibus-typing-booster searches for dictionaries in these directories:

```
  dirnames = [
        '/usr/share/hunspell',
        '/usr/share/myspell',
        '/usr/share/myspell/dicts',
        '/usr/local/share/hunspell', # On FreeBSD the dictionaries are here
        '/usr/local/share/myspell',
        '/usr/local/share/myspell/dicts',
    ]
```
According to your screenshot, the en_US dictionary was found, so it looks like the dictionaries are stored in one of these directories also on Linux mint.

**Comment by mike-fabian** [comment]
Yes, on Linux mint it looks like this:

```
mfabian@linuxmint:~$ dpkg-query -L hunspell-ne
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/hunspell-ne
/usr/share/doc/hunspell-ne/changelog.Debian.gz
/usr/share/doc/hunspell-ne/copyright
/usr/share/hunspell
/usr/share/hunspell/ne_NP.aff
/usr/share/hunspell/ne_NP.dic
mfabian@linuxmint:~$ 
```

So please select “ne_NP” instead of just ne in the setup tool of ibus-typing-booster, then it should work.

**Comment by mike-fabian** [comment]
Does  that work for  you? How well does ibus-typing-booster work for you for Nepalese?

**Comment by mike-fabian** [comment]
Ping?

**Comment by mike-fabian** [comment]
Ping?

**Comment by khumnath** [comment]
thank you mike now working
